/*
 Highcharts Gantt JS v8.0.4 (2020-04-28)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(g){"object"===typeof module&&module.exports?(g["default"]=g,module.exports=g):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(G){g(G);g.Highcharts=G;return g}):g("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(g){function G(g,d,w,p){g.hasOwnProperty(d)||(g[d]=p.apply(null,w))}g=g?g._modules:{};G(g,"parts-gantt/GridAxis.js",[g["parts/Axis.js"],g["parts/Globals.js"],g["parts/Tick.js"],g["parts/Utilities.js"]],function(g,d,w,p){var x=
p.addEvent,t=p.defined,y=p.erase,z=p.find,v=p.isArray,u=p.isNumber,h=p.merge,f=p.pick,n=p.timeUnits,D=p.wrap,F=d.dateFormat,B=d.Chart,m=function(c){var b=c.options;b.labels||(b.labels={});b.labels.align=f(b.labels.align,"center");c.categories||(b.showLastLabel=!1);c.labelRotation=0;b.labels.rotation=0};"";g.prototype.getMaxLabelDimensions=function(c,b){var a={width:0,height:0};b.forEach(function(b){b=c[b];if(p.isObject(b,!0)){var q=p.isObject(b.label,!0)?b.label:{};b=q.getBBox?q.getBBox().height:
0;q.textStr&&!u(q.textPxLength)&&(q.textPxLength=q.getBBox().width);q=u(q.textPxLength)?Math.round(q.textPxLength):0;a.height=Math.max(b,a.height);a.width=Math.max(q,a.width)}});return a};d.dateFormats.W=function(c){c=new this.Date(c);var b=(this.get("Day",c)+6)%7,a=new this.Date(c.valueOf());this.set("Date",a,this.get("Date",c)-b+3);b=new this.Date(this.get("FullYear",a),0,1);4!==this.get("Day",b)&&(this.set("Month",c,0),this.set("Date",c,1+(11-this.get("Day",b))%7));return(1+Math.floor((a.valueOf()-
b.valueOf())/6048E5)).toString()};d.dateFormats.E=function(c){return F("%a",c,!0).charAt(0)};x(B,"afterSetChartSize",function(){this.axes.forEach(function(c){(c.grid&&c.grid.columns||[]).forEach(function(b){b.setAxisSize();b.setAxisTranslation()})})});x(w,"afterGetLabelPosition",function(c){var b=this.label,a=this.axis,q=a.reversed,e=a.chart,H=a.options.grid||{},m=a.options.labels,f=m.align,A=k.Side[a.side],l=c.tickmarkOffset,r=a.tickPositions,C=this.pos-l;r=u(r[c.index+1])?r[c.index+1]-l:a.max+l;
var J=a.tickSize("tick",!0);l=v(J)?J[0]:0;J=J&&J[1]/2;if(!0===H.enabled){if("top"===A){H=a.top+a.offset;var I=H-l}else"bottom"===A?(I=e.chartHeight-a.bottom+a.offset,H=I+l):(H=a.top+a.len-a.translate(q?r:C),I=a.top+a.len-a.translate(q?C:r));"right"===A?(A=e.chartWidth-a.right+a.offset,q=A+l):"left"===A?(q=a.left+a.offset,A=q-l):(A=Math.round(a.left+a.translate(q?r:C))-J,q=Math.round(a.left+a.translate(q?C:r))-J);this.slotWidth=q-A;c.pos.x="left"===f?A:"right"===f?q:A+(q-A)/2;c.pos.y=I+(H-I)/2;e=e.renderer.fontMetrics(m.style.fontSize,
b.element);b=b.getBBox().height;m.useHTML?c.pos.y+=e.b+-(b/2):(b=Math.round(b/e.h),c.pos.y+=(e.b-(e.h-e.f))/2+-((b-1)*e.h/2));c.pos.x+=a.horiz&&m.x||0}});var e=function(){function c(b){this.axis=b}c.prototype.isOuterAxis=function(){var b=this.axis,a=b.grid.columnIndex,c=b.linkedParent&&b.linkedParent.grid.columns||b.grid.columns,e=a?b.linkedParent:b,k=-1,m=0;b.chart[b.coll].forEach(function(a,c){a.side!==b.side||a.options.isInternal||(m=c,a===e&&(k=c))});return m===k&&(u(a)?c.length===a:!0)};return c}(),
k=function(){function c(){}c.compose=function(b){g.keepProps.push("grid");D(b.prototype,"unsquish",c.wrapUnsquish);x(b,"init",c.onInit);x(b,"afterGetOffset",c.onAfterGetOffset);x(b,"afterGetTitlePosition",c.onAfterGetTitlePosition);x(b,"afterInit",c.onAfterInit);x(b,"afterRender",c.onAfterRender);x(b,"afterSetAxisTranslation",c.onAfterSetAxisTranslation);x(b,"afterSetOptions",c.onAfterSetOptions);x(b,"afterSetOptions",c.onAfterSetOptions2);x(b,"afterSetScale",c.onAfterSetScale);x(b,"afterTickSize",
c.onAfterTickSize);x(b,"trimTicks",c.onTrimTicks);x(b,"destroy",c.onDestroy)};c.onAfterGetOffset=function(){var b=this.grid;(b&&b.columns||[]).forEach(function(a){a.getOffset()})};c.onAfterGetTitlePosition=function(b){if(!0===(this.options.grid||{}).enabled){var a=this.axisTitle,q=this.height,e=this.horiz,k=this.left,m=this.offset,n=this.opposite,A=this.options.title,l=void 0===A?{}:A;A=this.top;var r=this.width,C=this.tickSize(),J=a&&a.getBBox().width,I=l.x||0,S=l.y||0,h=f(l.margin,e?5:10);a=this.chart.renderer.fontMetrics(l.style&&
l.style.fontSize,a).f;C=(e?A+q:k)+C[0]/2*(n?-1:1)*(e?1:-1)+(this.side===c.Side.bottom?a:0);b.titlePosition.x=e?k-J/2-h+I:C+(n?r:0)+m+I;b.titlePosition.y=e?C-(n?q:0)+(n?a:-a)/2+m+S:A-h+S}};c.onAfterInit=function(){var b=this.chart,a=this.options.grid;a=void 0===a?{}:a;var c=this.userOptions;a.enabled&&(m(this),D(this,"labelFormatter",function(a){var b=this.axis,c=this.value,r=b.tickPositions,q=(b.isLinked?b.linkedParent:b).series[0],e=c===r[0];r=c===r[r.length-1];q=q&&z(q.options.data,function(a){return a[b.isXAxis?
"x":"y"]===c});this.isFirst=e;this.isLast=r;this.point=q;return a.call(this)}));if(a.columns)for(var e=this.grid.columns=[],k=this.grid.columnIndex=0;++k<a.columns.length;){var f=h(c,a.columns[a.columns.length-k-1],{linkedTo:0,type:"category"});delete f.grid.columns;f=new g(this.chart,f);f.grid.isColumn=!0;f.grid.columnIndex=k;y(b.axes,f);y(b[this.coll],f);e.push(f)}};c.onAfterRender=function(){var b=this.grid,a=this.options,q=this.chart.renderer;if(!0===(a.grid||{}).enabled){this.maxLabelDimensions=
this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine){var e=a.lineWidth;if(e){var k=this.getLinePath(e),m=k[0],f=k[1],A=(this.tickSize("tick")[0]-1)*(this.side===c.Side.top||this.side===c.Side.left?-1:1);"M"===m[0]&&"L"===f[0]&&(this.horiz?(m[2]+=A,f[2]+=A):(m[1]+=A,f[1]+=A));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:k}):(this.grid.axisLineExtra=q.path(k).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),
q.styledMode||this.grid.axisLineExtra.attr({stroke:a.lineColor,"stroke-width":e}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(b&&b.columns||[]).forEach(function(a){a.render()})}};c.onAfterSetAxisTranslation=function(){var b=this.tickPositions&&this.tickPositions.info,a=this.options,c=a.grid||{},e=this.userOptions.labels||{};this.horiz&&(!0===c.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),b&&a.dateTimeLabelFormats&&a.labels&&!t(e.align)&&(!1===a.dateTimeLabelFormats[b.unitName].range||
1<b.count)&&(a.labels.align="left",t(e.x)||(a.labels.x=3)))};c.onAfterSetOptions=function(b){var a=this.options;b=b.userOptions;var c=a&&p.isObject(a.grid,!0)?a.grid:{};if(!0===c.enabled){var e=h(!0,{className:"highcharts-grid-axis "+(b.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,
rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},b);"xAxis"===this.coll&&(t(b.linkedTo)&&!t(b.tickPixelInterval)&&(e.tickPixelInterval=350),t(b.tickPixelInterval)||!t(b.linkedTo)||t(b.tickPositioner)||t(b.tickInterval)||(e.tickPositioner=function(a,b){var c=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(c){var q,l=e.units;for(q=0;q<l.length;q++)if(l[q][0]===
c.unitName){var r=q;break}if(l[r+1]){var C=l[r+1][0];var k=(l[r+1][1]||[1])[0]}else"year"===c.unitName&&(C="year",k=10*c.count);c=n[C];this.tickInterval=c*k;return this.getTimeTicks({unitRange:c,count:k,unitName:C},a,b,this.options.startOfWeek)}}));h(!0,this.options,e);this.horiz&&(a.minPadding=f(b.minPadding,0),a.maxPadding=f(b.maxPadding,0));u(a.grid.borderWidth)&&(a.tickWidth=a.lineWidth=c.borderWidth)}};c.onAfterSetOptions2=function(b){b=(b=b.userOptions)&&b.grid||{};var a=b.columns;b.enabled&&
a&&h(!0,this.options,a[a.length-1])};c.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(b){b.setScale()})};c.onAfterTickSize=function(b){var a=g.defaultLeftAxisOptions,c=this.horiz,e=this.maxLabelDimensions,k=this.options.grid;k=void 0===k?{}:k;k.enabled&&e&&(a=2*Math.abs(a.labels.x),c=c?k.cellHeight||a+e.height:a+e.width,v(b.tickSize)?b.tickSize[0]=c:b.tickSize=[c])};c.onDestroy=function(b){var a=this.grid;(a.columns||[]).forEach(function(a){a.destroy(b.keepEvents)});a.columns=
void 0};c.onInit=function(b){b=b.userOptions||{};var a=b.grid||{};a.enabled&&t(a.borderColor)&&(b.tickColor=b.lineColor=a.borderColor);this.grid||(this.grid=new e(this))};c.onTrimTicks=function(){var b=this.options,a=this.categories,c=this.tickPositions,e=c[0],k=c[c.length-1],m=this.linkedParent&&this.linkedParent.min||this.min,f=this.linkedParent&&this.linkedParent.max||this.max,A=this.tickInterval;!0!==(b.grid||{}).enabled||a||!this.horiz&&!this.isLinked||(e<m&&e+A>m&&!b.startOnTick&&(c[0]=m),k>
f&&k-A<f&&!b.endOnTick&&(c[c.length-1]=f))};c.wrapUnsquish=function(b){var a=this.options.grid;return!0===(void 0===a?{}:a).enabled&&this.categories?this.tickInterval:b.apply(this,Array.prototype.slice.call(arguments,1))};return c}();(function(c){c=c.Side||(c.Side={});c[c.top=0]="top";c[c.right=1]="right";c[c.bottom=2]="bottom";c[c.left=3]="left"})(k||(k={}));return k});G(g,"parts-gantt/Tree.js",[g["parts/Utilities.js"]],function(g){var d=g.extend,w=g.isNumber,p=g.pick,x=function(d,g){var v=d.reduce(function(u,
h){var f=p(h.parent,"");"undefined"===typeof u[f]&&(u[f]=[]);u[f].push(h);return u},{});Object.keys(v).forEach(function(u,h){var f=v[u];""!==u&&-1===g.indexOf(u)&&(f.forEach(function(f){h[""].push(f)}),delete h[u])});return v},t=function(y,g,v,u,h,f){var n=0,D=0,F=f&&f.after,B=f&&f.before;g={data:u,depth:v-1,id:y,level:v,parent:g};var m,e;"function"===typeof B&&B(g,f);B=(h[y]||[]).map(function(k){var c=t(k.id,y,v+1,k,h,f),b=k.start;k=!0===k.milestone?b:k.end;m=!w(m)||b<m?b:m;e=!w(e)||k>e?k:e;n=n+
1+c.descendants;D=Math.max(c.height+1,D);return c});u&&(u.start=p(u.start,m),u.end=p(u.end,e));d(g,{children:B,descendants:n,height:D});"function"===typeof F&&F(g,f);return g};return{getListOfParents:x,getNode:t,getTree:function(d,p){var v=d.map(function(u){return u.id});d=x(d,v);return t("",null,1,null,d,p)}}});G(g,"parts-gantt/TreeGridTick.js",[g["parts/Utilities.js"]],function(g){var d=g.addEvent,w=g.defined,p=g.isObject,x=g.isNumber,t=g.pick,y=g.wrap,z;(function(v){function u(){this.treeGrid||
(this.treeGrid=new F(this))}function h(f,m){f=f.treeGrid;var e=!f.labelIcon,k=m.renderer,c=m.xy,b=m.options,a=b.width,q=b.height,K=c.x-a/2-b.padding;c=c.y-q/2;var H=m.collapsed?90:180,n=m.show&&x(c),h=f.labelIcon;h||(f.labelIcon=h=k.path(k.symbols[b.type](b.x,b.y,a,q)).addClass("highcharts-label-icon").add(m.group));n||h.attr({y:-9999});k.styledMode||h.attr({"stroke-width":1,fill:t(m.color,"#666666")}).css({cursor:"pointer",stroke:b.lineColor,strokeWidth:b.lineWidth});h[e?"attr":"animate"]({translateX:K,
translateY:c,rotation:H})}function f(f,m,e,k,c,b,a,q,K){var H=t(this.options&&this.options.labels,b);b=this.pos;var n=this.axis,h="treegrid"===n.options.type;f=f.apply(this,[m,e,k,c,H,a,q,K]);h&&(m=H&&p(H.symbol,!0)?H.symbol:{},H=H&&x(H.indentation)?H.indentation:0,b=(b=(n=n.treeGrid.mapOfPosToGridNode)&&n[b])&&b.depth||1,f.x+=m.width+2*m.padding+(b-1)*H);return f}function n(f){var m=this,e=m.pos,k=m.axis,c=m.label,b=k.treeGrid.mapOfPosToGridNode,a=k.options,q=t(m.options&&m.options.labels,a&&a.labels),
K=q&&p(q.symbol,!0)?q.symbol:{},H=(b=b&&b[e])&&b.depth;a="treegrid"===a.type;var n=-1<k.tickPositions.indexOf(e);e=k.chart.styledMode;a&&b&&c&&c.element&&c.addClass("highcharts-treegrid-node-level-"+H);f.apply(m,Array.prototype.slice.call(arguments,1));a&&c&&c.element&&b&&b.descendants&&0<b.descendants&&(k=k.treeGrid.isCollapsed(b),h(m,{color:!e&&c.styles&&c.styles.color||"",collapsed:k,group:c.parentGroup,options:K,renderer:c.renderer,show:n,xy:c.xy}),K="highcharts-treegrid-node-"+(k?"expanded":
"collapsed"),c.addClass("highcharts-treegrid-node-"+(k?"collapsed":"expanded")).removeClass(K),e||c.css({cursor:"pointer"}),[c,m.treeGrid.labelIcon].forEach(function(a){a&&!a.attachedTreeGridEvents&&(d(a.element,"mouseover",function(){c.addClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:"underline"})}),d(a.element,"mouseout",function(){var a=w(q.style)?q.style:{};c.removeClass("highcharts-treegrid-node-active");c.renderer.styledMode||c.css({textDecoration:a.textDecoration})}),
d(a.element,"click",function(){m.treeGrid.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}var D=!1;v.compose=function(h){D||(d(h,"init",u),y(h.prototype,"getLabelPosition",f),y(h.prototype,"renderLabel",n),h.prototype.collapse=function(f){this.treeGrid.collapse(f)},h.prototype.expand=function(f){this.treeGrid.expand(f)},h.prototype.toggleCollapse=function(f){this.treeGrid.toggleCollapse(f)},D=!0)};var F=function(){function f(f){this.tick=f}f.prototype.collapse=function(f){var e=this.tick,k=e.axis,
c=k.brokenAxis;c&&k.treeGrid.mapOfPosToGridNode&&(e=k.treeGrid.collapse(k.treeGrid.mapOfPosToGridNode[e.pos]),c.setBreaks(e,t(f,!0)))};f.prototype.expand=function(f){var e=this.tick,k=e.axis,c=k.brokenAxis;c&&k.treeGrid.mapOfPosToGridNode&&(e=k.treeGrid.expand(k.treeGrid.mapOfPosToGridNode[e.pos]),c.setBreaks(e,t(f,!0)))};f.prototype.toggleCollapse=function(f){var e=this.tick,k=e.axis,c=k.brokenAxis;c&&k.treeGrid.mapOfPosToGridNode&&(e=k.treeGrid.toggleCollapse(k.treeGrid.mapOfPosToGridNode[e.pos]),
c.setBreaks(e,t(f,!0)))};return f}();v.Additions=F})(z||(z={}));return z});G(g,"mixins/tree-series.js",[g["parts/Color.js"],g["parts/Utilities.js"]],function(g,d){var w=d.extend,p=d.isArray,x=d.isNumber,t=d.isObject,y=d.merge,z=d.pick;return{getColor:function(v,u){var h=u.index,f=u.mapOptionsToLevel,n=u.parentColor,D=u.parentColorIndex,d=u.series,B=u.colors,m=u.siblings,e=d.points,k=d.chart.options.chart,c;if(v){e=e[v.i];v=f[v.level]||{};if(f=e&&v.colorByPoint){var b=e.index%(B?B.length:k.colorCount);
var a=B&&B[b]}if(!d.chart.styledMode){B=e&&e.options.color;k=v&&v.color;if(c=n)c=(c=v&&v.colorVariation)&&"brightness"===c.key?g.parse(n).brighten(h/m*c.to).get():n;c=z(B,k,a,c,d.color)}var q=z(e&&e.options.colorIndex,v&&v.colorIndex,b,D,u.colorIndex)}return{color:c,colorIndex:q}},getLevelOptions:function(d){var u=null;if(t(d)){u={};var h=x(d.from)?d.from:1;var f=d.levels;var n={};var D=t(d.defaults)?d.defaults:{};p(f)&&(n=f.reduce(function(f,n){if(t(n)&&x(n.level)){var m=y({},n);var e="boolean"===
typeof m.levelIsConstant?m.levelIsConstant:D.levelIsConstant;delete m.levelIsConstant;delete m.level;n=n.level+(e?0:h-1);t(f[n])?w(f[n],m):f[n]=m}return f},{}));f=x(d.to)?d.to:1;for(d=0;d<=f;d++)u[d]=y({},D,t(n[d])?n[d]:{})}return u},setTreeValues:function f(d,h){var n=h.before,D=h.idRoot,u=h.mapIdToNode[D],B=h.points[d.i],m=B&&B.options||{},e=0,k=[];w(d,{levelDynamic:d.level-(("boolean"===typeof h.levelIsConstant?h.levelIsConstant:1)?0:u.level),name:z(B&&B.name,""),visible:D===d.id||("boolean"===
typeof h.visible?h.visible:!1)});"function"===typeof n&&(d=n(d,h));d.children.forEach(function(c,b){var a=w({},h);w(a,{index:b,siblings:d.children.length,visible:d.visible});c=f(c,a);k.push(c);c.visible&&(e+=c.val)});d.visible=0<e||d.visible;n=z(m.value,e);w(d,{children:k,childrenTotal:e,isLeaf:d.visible&&!e,val:n});return d},updateRootId:function(d){if(t(d)){var h=t(d.options)?d.options:{};h=z(d.rootNode,h.rootId,"");t(d.userOptions)&&(d.userOptions.rootId=h);d.rootNode=h}return h}}});G(g,"modules/broken-axis.src.js",
[g["parts/Axis.js"],g["parts/Globals.js"],g["parts/Utilities.js"],g["parts/Stacking.js"]],function(g,d,w,p){var x=w.addEvent,t=w.find,y=w.fireEvent,z=w.isArray,v=w.isNumber,u=w.pick,h=d.Series,f=function(){function f(f){this.hasBreaks=!1;this.axis=f}f.isInBreak=function(f,h){var n=f.repeat||Infinity,m=f.from,e=f.to-f.from;h=h>=m?(h-m)%n:n-(m-h)%n;return f.inclusive?h<=e:h<e&&0!==h};f.lin2Val=function(h){var n=this.brokenAxis;n=n&&n.breakArray;if(!n)return h;var d;for(d=0;d<n.length;d++){var m=n[d];
if(m.from>=h)break;else m.to<h?h+=m.len:f.isInBreak(m,h)&&(h+=m.len)}return h};f.val2Lin=function(h){var n=this.brokenAxis;n=n&&n.breakArray;if(!n)return h;var d=h,m;for(m=0;m<n.length;m++){var e=n[m];if(e.to<=h)d-=e.len;else if(e.from>=h)break;else if(f.isInBreak(e,h)){d-=h-e.from;break}}return d};f.prototype.findBreakAt=function(f,h){return t(h,function(h){return h.from<f&&f<h.to})};f.prototype.isInAnyBreak=function(h,n){var d=this.axis,m=d.options.breaks,e=m&&m.length,k;if(e){for(;e--;)if(f.isInBreak(m[e],
h)){var c=!0;k||(k=u(m[e].showPoints,!d.isXAxis))}var b=c&&n?c&&!k:c}return b};f.prototype.setBreaks=function(h,n){var d=this,m=d.axis,e=z(h)&&!!h.length;m.isDirty=d.hasBreaks!==e;d.hasBreaks=e;m.options.breaks=m.userOptions.breaks=h;m.forceRedraw=!0;m.series.forEach(function(e){e.isDirty=!0});e||m.val2lin!==f.val2Lin||(delete m.val2lin,delete m.lin2val);e&&(m.userOptions.ordinal=!1,m.lin2val=f.lin2Val,m.val2lin=f.val2Lin,m.setExtremes=function(e,c,b,a,q){if(d.hasBreaks){for(var f,k=this.options.breaks;f=
d.findBreakAt(e,k);)e=f.to;for(;f=d.findBreakAt(c,k);)c=f.from;c<e&&(c=e)}g.prototype.setExtremes.call(this,e,c,b,a,q)},m.setAxisTranslation=function(e){g.prototype.setAxisTranslation.call(this,e);d.unitLength=null;if(d.hasBreaks){e=m.options.breaks||[];var c=[],b=[],a=0,q,k=m.userMin||m.min,h=m.userMax||m.max,n=u(m.pointRangePadding,0),E;e.forEach(function(a){q=a.repeat||Infinity;f.isInBreak(a,k)&&(k+=a.to%q-k%q);f.isInBreak(a,h)&&(h-=h%q-a.from%q)});e.forEach(function(a){l=a.from;for(q=a.repeat||
Infinity;l-q>k;)l-=q;for(;l<k;)l+=q;for(E=l;E<h;E+=q)c.push({value:E,move:"in"}),c.push({value:E+(a.to-a.from),move:"out",size:a.breakSize})});c.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var A=0;var l=k;c.forEach(function(c){A+="in"===c.move?1:-1;1===A&&"in"===c.move&&(l=c.value);0===A&&(b.push({from:l,to:c.value,len:c.value-l-(c.size||0)}),a+=c.value-l-(c.size||0))});m.breakArray=d.breakArray=b;d.unitLength=h-k-a+n;y(m,"afterBreaks");m.staticScale?
m.transA=m.staticScale:d.unitLength&&(m.transA*=(h-m.min+n)/d.unitLength);n&&(m.minPixelPadding=m.transA*m.minPointOffset);m.min=k;m.max=h}});u(n,!0)&&m.chart.redraw()};return f}();d=function(){function n(){}n.compose=function(n,d){n.keepProps.push("brokenAxis");var g=h.prototype;g.drawBreaks=function(f,e){var k=this,c=k.points,b,a,q,h;if(f&&f.brokenAxis&&f.brokenAxis.hasBreaks){var m=f.brokenAxis;e.forEach(function(e){b=m&&m.breakArray||[];a=f.isXAxis?f.min:u(k.options.threshold,f.min);c.forEach(function(c){h=
u(c["stack"+e.toUpperCase()],c[e]);b.forEach(function(b){if(v(a)&&v(h)){q=!1;if(a<b.from&&h>b.to||a>b.from&&h<b.from)q="pointBreak";else if(a<b.from&&h>b.from&&h<b.to||a>b.from&&h>b.to&&h<b.from)q="pointInBreak";q&&y(f,q,{point:c,brk:b})}})})})}};g.gappedPath=function(){var f=this.currentDataGrouping,e=f&&f.gapSize;f=this.options.gapSize;var k=this.points.slice(),c=k.length-1,b=this.yAxis,a;if(f&&0<c)for("value"!==this.options.gapUnit&&(f*=this.basePointRange),e&&e>f&&e>=this.basePointRange&&(f=e),
a=void 0;c--;)a&&!1!==a.visible||(a=k[c+1]),e=k[c],!1!==a.visible&&!1!==e.visible&&(a.x-e.x>f&&(a=(e.x+a.x)/2,k.splice(c+1,0,{isNull:!0,x:a}),b.stacking&&this.options.stacking&&(a=b.stacking.stacks[this.stackKey][a]=new p(b,b.options.stackLabels,!1,a,this.stack),a.total=0)),a=e);return this.getGraphPath(k)};x(n,"init",function(){this.brokenAxis||(this.brokenAxis=new f(this))});x(n,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});x(n,
"afterSetTickPositions",function(){var f=this.brokenAxis;if(f&&f.hasBreaks){var e=this.tickPositions,k=this.tickPositions.info,c=[],b;for(b=0;b<e.length;b++)f.isInAnyBreak(e[b])||c.push(e[b]);this.tickPositions=c;this.tickPositions.info=k}});x(n,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});x(d,"afterGeneratePoints",function(){var f=this.options.connectNulls,e=this.points,k=this.xAxis,c=this.yAxis;if(this.isDirty)for(var b=e.length;b--;){var a=
e[b],q=!(null===a.y&&!1===f)&&(k&&k.brokenAxis&&k.brokenAxis.isInAnyBreak(a.x,!0)||c&&c.brokenAxis&&c.brokenAxis.isInAnyBreak(a.y,!0));a.visible=q?!1:!1!==a.options.visible}});x(d,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,u(this.pointArrayMap,["y"]))})};return n}();d.compose(g,h);return d});G(g,"parts-gantt/TreeGridAxis.js",[g["parts/Axis.js"],g["parts-gantt/GridAxis.js"],g["parts/Tick.js"],g["parts-gantt/Tree.js"],g["parts-gantt/TreeGridTick.js"],g["mixins/tree-series.js"],
g["parts/Utilities.js"]],function(g,d,w,p,x,t,y){var z=y.addEvent,v=y.find,u=y.fireEvent,h=y.isNumber,f=y.isObject,n=y.isString,D=y.merge,F=y.pick,B=y.wrap,m;(function(e){function k(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}}function c(a,b,c){var l=[],e=[],r={},q={},k=-1,h="boolean"===typeof b?b:!1;a=p.getTree(a,{after:function(a){a=q[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=
c;a.height=b;a.collapsed&&e.push(a)},before:function(a){var b=f(a.data,!0)?a.data:{},c=n(b.name)?b.name:"",e=r[a.parent];e=f(e,!0)?q[e.pos]:null;var C=function(a){return a.name===c},I;h&&f(e,!0)&&(I=v(e.children,C))?(C=I.pos,I.nodes.push(a)):C=k++;q[C]||(q[C]=I={depth:e?e.depth+1:0,name:c,nodes:[a],children:[],pos:C},-1!==C&&l.push(c),f(e,!0)&&e.children.push(I));n(a.id)&&(r[a.id]=a);I&&!0===b.collapsed&&(I.collapsed=!0);a.pos=C}});q=function(a,b){var c=function(a,l,e){var r=l+(-1===l?0:b-1),q=(r-
l)/2,C=l+q;a.nodes.forEach(function(a){var b=a.data;f(b,!0)&&(b.y=l+(b.seriesIndex||0),delete b.seriesIndex);a.pos=C});e[C]=a;a.pos=C;a.tickmarkOffset=q+.5;a.collapseStart=r+.5;a.children.forEach(function(a){c(a,r+1,e);r=(a.collapseEnd||0)-.5});a.collapseEnd=r+.5;return e};return c(a["-1"],-1,{})}(q,c);return{categories:l,mapOfIdToNode:r,mapOfPosToGridNode:q,collapsedNodes:e,tree:a}}function b(a){a.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(b){var l=b.options||
{},e=l.labels,q=l.uniqueNames,k=0;if(!b.treeGrid.mapOfPosToGridNode||b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty}))l=b.series.reduce(function(a,b){b.visible&&((b.options.data||[]).forEach(function(b){f(b,!0)&&(b.seriesIndex=k,a.push(b))}),!0===q&&k++);return a},[]),l=c(l,q||!1,!0===q?k:1),b.categories=l.categories,b.treeGrid.mapOfPosToGridNode=l.mapOfPosToGridNode,b.hasNames=!0,b.treeGrid.tree=l.tree,b.series.forEach(function(a){var b=(a.options.data||[]).map(function(a){return f(a,
!0)?D(a):a});a.visible&&a.setData(b,!1)}),b.treeGrid.mapOptionsToLevel=t.getLevelOptions({defaults:e,from:1,levels:e&&e.levels,to:b.treeGrid.tree&&b.treeGrid.tree.height}),"beforeRender"===a.type&&(b.treeGrid.collapsedNodes=l.collapsedNodes)})}function a(a,b){var c=this.treeGrid.mapOptionsToLevel||{},l=this.ticks,e=l[b],q;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var f=this.treeGrid.mapOfPosToGridNode[b];(c=c[f.depth])&&(q={labels:c});e?(e.parameters.category=f.name,e.options=
q,e.addLabel()):l[b]=new w(this,b,void 0,void 0,{category:f.name,tickmarkOffset:f.tickmarkOffset,options:q})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function q(a){var b=this.options;b=(b=b&&b.labels)&&h(b.indentation)?b.indentation:0;var c=a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var e=this.treeGrid.mapOfPosToGridNode[-1].height||0;c.width+=b*(e-1)}return c}function m(a,l,e){var q=this,f="treegrid"===
e.type;q.treeGrid||(q.treeGrid=new E(q));f&&(z(l,"beforeRender",b),z(l,"beforeRedraw",b),z(l,"addSeries",function(a){a.options.data&&(a=c(a.options.data,e.uniqueNames||!1,1),q.treeGrid.collapsedNodes=(q.treeGrid.collapsedNodes||[]).concat(a.collapsedNodes))}),z(q,"foundExtremes",function(){q.treeGrid.collapsedNodes&&q.treeGrid.collapsedNodes.forEach(function(a){var b=q.treeGrid.collapse(a);q.brokenAxis&&(q.brokenAxis.setBreaks(b,!1),q.treeGrid.collapsedNodes&&(q.treeGrid.collapsedNodes=q.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==
b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),e=D({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},e,{reversed:!0,grid:{columns:void 0}}));a.apply(q,[l,e]);f&&(q.hasNames=!0,q.options.showLastLabel=!0)}function H(a){var b=this.options;"treegrid"===b.type?(this.min=F(this.userMin,b.min,this.dataMin),this.max=F(this.userMax,b.max,this.dataMax),u(this,"foundExtremes"),
this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var g=!1;e.compose=function(b){g||(d.compose(b),B(b.prototype,"generateTick",a),B(b.prototype,"getMaxLabelDimensions",q),B(b.prototype,"init",m),B(b.prototype,"setTickInterval",H),x.compose(w),g=!0)};var E=function(){function a(a){this.axis=a}a.prototype.collapse=function(a){var b=this.axis,
c=b.options.breaks||[];a=k(a,b.max);c.push(a);return c};a.prototype.expand=function(a){var b=this.axis,c=b.options.breaks||[],l=k(a,b.max);return c.reduce(function(a,b){b.to===l.to&&b.from===l.from||a.push(b);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(b,c){c=+c;!(a.min<=c&&a.max>=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(c)||b.push(c);return b},[])};a.prototype.isCollapsed=function(a){var b=this.axis,
c=b.options.breaks||[],e=k(a,b.max);return c.some(function(a){return a.from===e.from&&a.to===e.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();e.Additions=E})(m||(m={}));g.prototype.utils={getNode:p.getNode};return m});G(g,"parts-gantt/CurrentDateIndicator.js",[g["parts/Globals.js"],g["parts/Utilities.js"],g["parts/PlotLineOrBand.js"]],function(g,d,w){var p=d.addEvent,x=d.merge;d=d.wrap;var t={currentDateIndicator:!0,color:"#ccd6eb",
width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(d,p){return g.dateFormat(p,d)},rotation:0,style:{fontSize:"10px"}}};p(g.Axis,"afterSetOptions",function(){var d=this.options,g=d.currentDateIndicator;g&&(g="object"===typeof g?x(t,g):x(t),g.value=new Date,d.plotLines||(d.plotLines=[]),d.plotLines.push(g))});p(w,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});d(w.prototype,"getLabelText",function(d,g){var p=this.options;return p.currentDateIndicator&&
p.label&&"function"===typeof p.label.formatter?(p.value=new Date,p.label.formatter.call(this,p.value,p.label.format)):d.call(this,g)})});G(g,"modules/static-scale.src.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,d){var w=d.addEvent,p=d.defined,x=d.isNumber,t=d.pick;d=g.Chart;w(g.Axis,"afterSetOptions",function(){var d=this.chart.options&&this.chart.options.chart;!this.horiz&&x(this.options.staticScale)&&(!d.height||d.scrollablePlotArea&&d.scrollablePlotArea.minHeight)&&(this.staticScale=
this.options.staticScale)});d.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&((this.axes||[]).forEach(function(d){var g=d.chart,v=!!g.initiatedScale&&g.options.animation,u=d.options.staticScale;if(d.staticScale&&p(d.min)){var h=t(d.brokenAxis&&d.brokenAxis.unitLength,d.max+d.tickInterval-d.min)*u;h=Math.max(h,u);u=h-g.plotHeight;1<=Math.abs(u)&&(g.plotHeight=h,g.redrawTrigger="adjustHeight",g.setSize(void 0,g.chartHeight+u,v));d.series.forEach(function(f){(f=f.sharedClipKey&&
g[f.sharedClipKey])&&f.attr({height:g.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=null};w(d,"render",d.prototype.adjustHeight)});G(g,"parts-gantt/PathfinderAlgorithms.js",[g["parts/Utilities.js"]],function(g){function d(h,f,d){d=d||0;var n=h.length-1;f-=1e-7;for(var g,p;d<=n;)if(g=n+d>>1,p=f-h[g].xMin,0<p)d=g+1;else if(0>p)n=g-1;else return g;return 0<d?d-1:0}function w(h,f){for(var n=d(h,f.x+1)+1;n--;){var g;if(g=h[n].xMax>=f.x)g=h[n],g=f.x<=g.xMax&&f.x>=g.xMin&&f.y<=g.yMax&&f.y>=
g.yMin;if(g)return n}return-1}function p(d){var f=[];if(d.length){f.push(["M",d[0].start.x,d[0].start.y]);for(var h=0;h<d.length;++h)f.push(["L",d[h].end.x,d[h].end.y])}return f}function x(d,f){d.yMin=v(d.yMin,f.yMin);d.yMax=z(d.yMax,f.yMax);d.xMin=v(d.xMin,f.xMin);d.xMax=z(d.xMax,f.xMax)}var t=g.extend,y=g.pick,z=Math.min,v=Math.max,u=Math.abs;return{straight:function(d,f){return{path:[["M",d.x,d.y],["L",f.x,f.y]],obstacles:[{start:d,end:f}]}},simpleConnect:t(function(d,f,n){function h(a,b,c,e,f){a=
{x:a.x,y:a.y};a[b]=c[e||b]+(f||0);return a}function g(a,b,c){var e=u(b[c]-a[c+"Min"])>u(b[c]-a[c+"Max"]);return h(b,c,a,c+(e?"Max":"Min"),e?1:-1)}var v=[],m=y(n.startDirectionX,u(f.x-d.x)>u(f.y-d.y))?"x":"y",e=n.chartObstacles,k=w(e,d);n=w(e,f);if(-1<n){var c=e[n];n=g(c,f,m);c={start:n,end:f};var b=n}else b=f;-1<k&&(e=e[k],n=g(e,d,m),v.push({start:d,end:n}),n[m]>=d[m]===n[m]>=b[m]&&(m="y"===m?"x":"y",f=d[m]<f[m],v.push({start:n,end:h(n,m,e,m+(f?"Max":"Min"),f?1:-1)}),m="y"===m?"x":"y"));d=v.length?
v[v.length-1].end:d;n=h(d,m,b);v.push({start:d,end:n});m=h(n,"y"===m?"x":"y",b);v.push({start:n,end:m});v.push(c);return{path:p(v),obstacles:v}},{requiresObstacles:!0}),fastAvoid:t(function(h,f,n){function g(a,b,c){var e,l=a.x<b.x?1:-1;if(a.x<b.x){var q=a;var f=b}else q=b,f=a;if(a.y<b.y){var r=a;var k=b}else r=b,k=a;for(e=0>l?z(d(E,f.x),E.length-1):0;E[e]&&(0<l&&E[e].xMin<=f.x||0>l&&E[e].xMax>=q.x);){if(E[e].xMin<=f.x&&E[e].xMax>=q.x&&E[e].yMin<=k.y&&E[e].yMax>=r.y)return c?{y:a.y,x:a.x<b.x?E[e].xMin-
1:E[e].xMax+1,obstacle:E[e]}:{x:a.x,y:a.y<b.y?E[e].yMin-1:E[e].yMax+1,obstacle:E[e]};e+=l}return b}function t(a,b,c,e,l){var q=l.soft,f=l.hard,r=e?"x":"y",k={x:b.x,y:b.y},d={x:b.x,y:b.y};l=a[r+"Max"]>=q[r+"Max"];q=a[r+"Min"]<=q[r+"Min"];var C=a[r+"Max"]>=f[r+"Max"];f=a[r+"Min"]<=f[r+"Min"];var h=u(a[r+"Min"]-b[r]),m=u(a[r+"Max"]-b[r]);c=10>u(h-m)?b[r]<c[r]:m<h;d[r]=a[r+"Min"];k[r]=a[r+"Max"];a=g(b,d,e)[r]!==d[r];b=g(b,k,e)[r]!==k[r];c=a?b?c:!0:b?!1:c;c=q?l?c:!0:l?!1:c;return f?C?c:!0:C?!1:c}function B(a,
c,e){if(a.x===c.x&&a.y===c.y)return[];var l=e?"x":"y",f=n.obstacleOptions.margin;var r={soft:{xMin:q,xMax:K,yMin:H,yMax:V},hard:n.hardBounds};var k=w(E,a);if(-1<k){k=E[k];r=t(k,a,c,e,r);x(k,n.hardBounds);var d=e?{y:a.y,x:k[r?"xMax":"xMin"]+(r?1:-1)}:{x:a.x,y:k[r?"yMax":"yMin"]+(r?1:-1)};var h=w(E,d);-1<h&&(h=E[h],x(h,n.hardBounds),d[l]=r?v(k[l+"Max"]-f+1,(h[l+"Min"]+k[l+"Max"])/2):z(k[l+"Min"]+f-1,(h[l+"Max"]+k[l+"Min"])/2),a.x===d.x&&a.y===d.y?(b&&(d[l]=r?v(k[l+"Max"],h[l+"Max"])+1:z(k[l+"Min"],
h[l+"Min"])-1),b=!b):b=!1);a=[{start:a,end:d}]}else l=g(a,{x:e?c.x:a.x,y:e?a.y:c.y},e),a=[{start:a,end:{x:l.x,y:l.y}}],l[e?"x":"y"]!==c[e?"x":"y"]&&(r=t(l.obstacle,l,c,!e,r),x(l.obstacle,n.hardBounds),r={x:e?l.x:l.obstacle[r?"xMax":"xMin"]+(r?1:-1),y:e?l.obstacle[r?"yMax":"yMin"]+(r?1:-1):l.y},e=!e,a=a.concat(B({x:l.x,y:l.y},r,e)));return a=a.concat(B(a[a.length-1].end,c,!e))}function m(a,b,c){var e=z(a.xMax-b.x,b.x-a.xMin)<z(a.yMax-b.y,b.y-a.yMin);c=t(a,b,c,e,{soft:n.hardBounds,hard:n.hardBounds});
return e?{y:b.y,x:a[c?"xMax":"xMin"]+(c?1:-1)}:{x:b.x,y:a[c?"yMax":"yMin"]+(c?1:-1)}}var e=y(n.startDirectionX,u(f.x-h.x)>u(f.y-h.y)),k=e?"x":"y",c=[],b=!1,a=n.obstacleMetrics,q=z(h.x,f.x)-a.maxWidth-10,K=v(h.x,f.x)+a.maxWidth+10,H=z(h.y,f.y)-a.maxHeight-10,V=v(h.y,f.y)+a.maxHeight+10,E=n.chartObstacles;var A=d(E,q);a=d(E,K);E=E.slice(A,a+1);if(-1<(a=w(E,f))){var l=m(E[a],f,h);c.push({end:f,start:l});f=l}for(;-1<(a=w(E,f));)A=0>f[k]-h[k],l={x:f.x,y:f.y},l[k]=E[a][A?k+"Max":k+"Min"]+(A?1:-1),c.push({end:f,
start:l}),f=l;h=B(h,f,e);h=h.concat(c.reverse());return{path:p(h),obstacles:h}},{requiresObstacles:!0})}});G(g,"parts-gantt/ArrowSymbols.js",[g["parts/Globals.js"]],function(g){g.SVGRenderer.prototype.symbols.arrow=function(d,g,p,x){return[["M",d,g+x/2],["L",d+p,g],["L",d,g+x/2],["L",d+p,g+x]]};g.SVGRenderer.prototype.symbols["arrow-half"]=function(d,w,p,x){return g.SVGRenderer.prototype.symbols.arrow(d,w,p/2,x)};g.SVGRenderer.prototype.symbols["triangle-left"]=function(d,g,p,x){return[["M",d+p,g],
["L",d,g+x/2],["L",d+p,g+x],["Z"]]};g.SVGRenderer.prototype.symbols["arrow-filled"]=g.SVGRenderer.prototype.symbols["triangle-left"];g.SVGRenderer.prototype.symbols["triangle-left-half"]=function(d,w,p,x){return g.SVGRenderer.prototype.symbols["triangle-left"](d,w,p/2,x)};g.SVGRenderer.prototype.symbols["arrow-filled-half"]=g.SVGRenderer.prototype.symbols["triangle-left-half"]});G(g,"parts-gantt/Pathfinder.js",[g["parts/Globals.js"],g["parts/Point.js"],g["parts/Utilities.js"],g["parts-gantt/PathfinderAlgorithms.js"]],
function(g,d,w,p){function x(b){var a=b.shapeArgs;return a?{xMin:a.x,xMax:a.x+a.width,yMin:a.y,yMax:a.y+a.height}:(a=b.graphic&&b.graphic.getBBox())?{xMin:b.plotX-a.width/2,xMax:b.plotX+a.width/2,yMin:b.plotY-a.height/2,yMax:b.plotY+a.height/2}:null}function t(b){for(var a=b.length,e=0,f,d,h=[],g=function(a,b,e){e=B(e,10);var l=a.yMax+e>b.yMin-e&&a.yMin-e<b.yMax+e,q=a.xMax+e>b.xMin-e&&a.xMin-e<b.xMax+e,f=l?a.xMin>b.xMax?a.xMin-b.xMax:b.xMin-a.xMax:Infinity,r=q?a.yMin>b.yMax?a.yMin-b.yMax:b.yMin-a.yMax:
Infinity;return q&&l?e?g(a,b,Math.floor(e/2)):Infinity:c(f,r)};e<a;++e)for(f=e+1;f<a;++f)d=g(b[e],b[f]),80>d&&h.push(d);h.push(80);return k(Math.floor(h.sort(function(a,b){return a-b})[Math.floor(h.length/10)]/2-1),1)}function y(b,a,c){this.init(b,a,c)}function z(b){this.init(b)}function v(b){if(b.options.pathfinder||b.series.reduce(function(a,b){b.options&&D(!0,b.options.connectors=b.options.connectors||{},b.options.pathfinder);return a||b.options&&b.options.pathfinder},!1))D(!0,b.options.connectors=
b.options.connectors||{},b.options.pathfinder),f('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}"";var u=w.addEvent,h=w.defined,f=w.error,n=w.extend,D=w.merge,F=w.objectEach,B=w.pick,m=w.splat,e=g.deg2rad,k=Math.max,c=Math.min;n(g.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});y.prototype=
{init:function(b,a,c){this.fromPoint=b;this.toPoint=a;this.options=c;this.chart=b.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(b,a,c){var e=this.chart,f=e.styledMode,q=e.pathfinder,k=!e.options.chart.forExport&&!1!==c,d=this.graphics&&this.graphics.path;q.group||(q.group=e.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(e.seriesGroup));q.group.translate(e.plotLeft,e.plotTop);d&&d.renderer||(d=e.renderer.path().add(q.group),f||d.attr({opacity:0}));
d.attr(a);b={d:b};f||(b.opacity=1);d[k?"animate":"attr"](b,c);this.graphics=this.graphics||{};this.graphics.path=d},addMarker:function(b,a,c){var f=this.fromPoint.series.chart,q=f.pathfinder;f=f.renderer;var d="start"===b?this.fromPoint:this.toPoint,k=d.getPathfinderAnchorPoint(a);if(a.enabled&&((c="start"===b?c[1]:c[c.length-2])&&"M"===c[0]||"L"===c[0])){c={x:c[1],y:c[2]};c=d.getRadiansToVector(c,k);k=d.getMarkerVector(c,a.radius,k);c=-c/e;if(a.width&&a.height){var h=a.width;var l=a.height}else h=
l=2*a.radius;this.graphics=this.graphics||{};k={x:k.x-h/2,y:k.y-l/2,width:h,height:l,rotation:c,rotationOriginX:k.x,rotationOriginY:k.y};this.graphics[b]?this.graphics[b].animate(k):(this.graphics[b]=f.symbol(a.symbol).addClass("highcharts-point-connecting-path-"+b+"-marker").attr(k).add(q.group),f.styledMode||this.graphics[b].attr({fill:a.color||this.fromPoint.color,stroke:a.lineColor,"stroke-width":a.lineWidth,opacity:0}).animate({opacity:1},d.series.options.animation))}},getPath:function(b){var a=
this.pathfinder,c=this.chart,e=a.algorithms[b.type],k=a.chartObstacles;if("function"!==typeof e)f('"'+b.type+'" is not a Pathfinder algorithm.');else return e.requiresObstacles&&!k&&(k=a.chartObstacles=a.getChartObstacles(b),c.options.connectors.algorithmMargin=b.algorithmMargin,a.chartObstacleMetrics=a.getObstacleMetrics(k)),e(this.fromPoint.getPathfinderAnchorPoint(b.startMarker),this.toPoint.getPathfinderAnchorPoint(b.endMarker),D({chartObstacles:k,lineObstacles:a.lineObstacles||[],obstacleMetrics:a.chartObstacleMetrics,
hardBounds:{xMin:0,xMax:c.plotWidth,yMin:0,yMax:c.plotHeight},obstacleOptions:{margin:b.algorithmMargin},startDirectionX:a.getAlgorithmStartDirection(b.startMarker)},b))},render:function(){var b=this.fromPoint,a=b.series,e=a.chart,f=e.pathfinder,d=D(e.options.connectors,a.options.connectors,b.options.connectors,this.options),g={};e.styledMode||(g.stroke=d.lineColor||b.color,g["stroke-width"]=d.lineWidth,d.dashStyle&&(g.dashstyle=d.dashStyle));g["class"]="highcharts-point-connecting-path highcharts-color-"+
b.colorIndex;d=D(g,d);h(d.marker.radius)||(d.marker.radius=c(k(Math.ceil((d.algorithmMargin||8)/2)-1,1),5));b=this.getPath(d);e=b.path;b.obstacles&&(f.lineObstacles=f.lineObstacles||[],f.lineObstacles=f.lineObstacles.concat(b.obstacles));this.renderPath(e,g,a.options.animation);this.addMarker("start",D(d.marker,d.startMarker),e);this.addMarker("end",D(d.marker,d.endMarker),e)},destroy:function(){this.graphics&&(F(this.graphics,function(b){b.destroy()}),delete this.graphics)}};z.prototype={algorithms:p,
init:function(b){this.chart=b;this.connections=[];u(b,"redraw",function(){this.pathfinder.update()})},update:function(b){var a=this.chart,c=this,e=c.connections;c.connections=[];a.series.forEach(function(b){b.visible&&!b.options.isInternal&&b.points.forEach(function(b){var e,l=b.options&&b.options.connect&&m(b.options.connect);b.visible&&!1!==b.isInside&&l&&l.forEach(function(l){e=a.get("string"===typeof l?l:l.to);e instanceof d&&e.series.visible&&e.visible&&!1!==e.isInside&&c.connections.push(new y(b,
e,"string"===typeof l?{}:l))})})});for(var f=0,k,h,g=e.length,l=c.connections.length;f<g;++f){h=!1;for(k=0;k<l;++k)if(e[f].fromPoint===c.connections[k].fromPoint&&e[f].toPoint===c.connections[k].toPoint){c.connections[k].graphics=e[f].graphics;h=!0;break}h||e[f].destroy()}delete this.chartObstacles;delete this.lineObstacles;c.renderConnections(b)},renderConnections:function(b){b?this.chart.series.forEach(function(a){var b=function(){var b=a.chart.pathfinder;(b&&b.connections||[]).forEach(function(b){b.fromPoint&&
b.fromPoint.series===a&&b.render()});a.pathfinderRemoveRenderEvent&&(a.pathfinderRemoveRenderEvent(),delete a.pathfinderRemoveRenderEvent)};!1===a.options.animation?b():a.pathfinderRemoveRenderEvent=u(a,"afterAnimate",b)}):this.connections.forEach(function(a){a.render()})},getChartObstacles:function(b){for(var a=[],c=this.chart.series,e=B(b.algorithmMargin,0),f,k=0,d=c.length;k<d;++k)if(c[k].visible&&!c[k].options.isInternal)for(var g=0,l=c[k].points.length,r;g<l;++g)r=c[k].points[g],r.visible&&(r=
x(r))&&a.push({xMin:r.xMin-e,xMax:r.xMax+e,yMin:r.yMin-e,yMax:r.yMax+e});a=a.sort(function(a,b){return a.xMin-b.xMin});h(b.algorithmMargin)||(f=b.algorithmMargin=t(a),a.forEach(function(a){a.xMin-=f;a.xMax+=f;a.yMin-=f;a.yMax+=f}));return a},getObstacleMetrics:function(b){for(var a=0,c=0,e,f,k=b.length;k--;)e=b[k].xMax-b[k].xMin,f=b[k].yMax-b[k].yMin,a<e&&(a=e),c<f&&(c=f);return{maxHeight:c,maxWidth:a}},getAlgorithmStartDirection:function(b){var a="top"!==b.verticalAlign&&"bottom"!==b.verticalAlign;
return"left"!==b.align&&"right"!==b.align?a?void 0:!1:a?!0:void 0}};g.Connection=y;g.Pathfinder=z;n(d.prototype,{getPathfinderAnchorPoint:function(b){var a=x(this);switch(b.align){case "right":var c="xMax";break;case "left":c="xMin"}switch(b.verticalAlign){case "top":var e="yMin";break;case "bottom":e="yMax"}return{x:c?a[c]:(a.xMin+a.xMax)/2,y:e?a[e]:(a.yMin+a.yMax)/2}},getRadiansToVector:function(b,a){var c;h(a)||(c=x(this))&&(a={x:(c.xMin+c.xMax)/2,y:(c.yMin+c.yMax)/2});return Math.atan2(a.y-b.y,
b.x-a.x)},getMarkerVector:function(b,a,c){var e=2*Math.PI,f=x(this),k=f.xMax-f.xMin,d=f.yMax-f.yMin,q=Math.atan2(d,k),l=!1;k/=2;var r=d/2,h=f.xMin+k;f=f.yMin+r;for(var g=h,m=f,n={},p=1,L=1;b<-Math.PI;)b+=e;for(;b>Math.PI;)b-=e;e=Math.tan(b);b>-q&&b<=q?(L=-1,l=!0):b>q&&b<=Math.PI-q?L=-1:b>Math.PI-q||b<=-(Math.PI-q)?(p=-1,l=!0):p=-1;l?(g+=p*k,m+=L*k*e):(g+=d/(2*e)*p,m+=L*r);c.x!==h&&(g=c.x);c.y!==f&&(m=c.y);n.x=g+a*Math.cos(b);n.y=m-a*Math.sin(b);return n}});g.Chart.prototype.callbacks.push(function(b){!1!==
b.options.connectors.enabled&&(v(b),this.pathfinder=new z(this),this.pathfinder.update(!0))})});G(g,"modules/xrange.src.js",[g["parts/Globals.js"],g["parts/Color.js"],g["parts/Point.js"],g["parts/Utilities.js"]],function(g,d,w,p){var x=d.parse;d=p.addEvent;var t=p.clamp,y=p.correctFloat,z=p.defined,v=p.find,u=p.isNumber,h=p.isObject,f=p.merge,n=p.pick;p=p.seriesType;var D=g.seriesTypes.column,F=g.seriesTypes,B=g.Axis,m=g.Series;p("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var e=
this.point.partialFill;h(e)&&(e=e.amount);if(u(e)&&0<e)return y(100*e)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:F.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:g.noop,buildKDTree:g.noop,
init:function(){F.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function e(){f.series.forEach(function(b){var a=b.xAxis;b.xAxis=b.yAxis;b.yAxis=a})}var f=this.chart;e();var c=D.prototype.getColumnMetrics.call(this);e();return c},cropData:function(e,f,c,b){f=m.prototype.cropData.call(this,this.x2Data,f,c,b);f.xData=e.slice(f.start,f.end);return f},findPointIndex:function(e){var f=this.cropped,c=this.cropStart,b=this.points,a=e.id;if(a)var d=(d=
v(b,function(b){return b.id===a}))?d.index:void 0;"undefined"===typeof d&&(d=(d=v(b,function(a){return a.x===e.x&&a.x2===e.x2&&!a.touched}))?d.index:void 0);f&&u(d)&&u(c)&&d>=c&&(d-=c);return d},translatePoint:function(e){var d=this.xAxis,c=this.yAxis,b=this.columnMetrics,a=this.options,q=a.minPointLength||0,g=e.plotX,m=n(e.x2,e.x+(e.len||0)),p=d.translate(m,0,0,0,1);m=Math.abs(p-g);var v=this.chart.inverted,A=n(a.borderWidth,1)%2/2,l=b.offset,r=Math.round(b.width);q&&(q-=m,0>q&&(q=0),g-=q/2,p+=q/
2);g=Math.max(g,-10);p=t(p,-10,d.len+10);z(e.options.pointWidth)&&(l-=(Math.ceil(e.options.pointWidth)-r)/2,r=Math.ceil(e.options.pointWidth));a.pointPlacement&&u(e.plotY)&&c.categories&&(e.plotY=c.translate(e.y,0,1,0,1,a.pointPlacement));e.shapeArgs={x:Math.floor(Math.min(g,p))+A,y:Math.floor(e.plotY+l)+A,width:Math.round(Math.abs(p-g)),height:r,r:this.options.borderRadius};a=e.shapeArgs.x;q=a+e.shapeArgs.width;0>a||q>d.len?(a=t(a,0,d.len),q=t(q,0,d.len),p=q-a,e.dlBox=f(e.shapeArgs,{x:a,width:q-
a,centerX:p?p/2:null})):e.dlBox=null;a=e.tooltipPos;q=v?1:0;p=v?0:1;b=this.columnMetrics?this.columnMetrics.offset:-b.width/2;a[q]=t(a[q]+m/2*(d.reversed?-1:1)*(v?-1:1),0,d.len-1);a[p]=t(a[p]+(v?-1:1)*b,0,c.len-1);if(b=e.partialFill)h(b)&&(b=b.amount),u(b)||(b=0),c=e.shapeArgs,e.partShapeArgs={x:c.x,y:c.y,width:c.width,height:c.height,r:this.options.borderRadius},g=Math.max(Math.round(m*b+e.plotX-g),0),e.clipRectArgs={x:d.reversed?c.x+m-g:c.x,y:c.y,width:g,height:c.height}},translate:function(){D.prototype.translate.apply(this,
arguments);this.points.forEach(function(e){this.translatePoint(e)},this)},drawPoint:function(e,d){var c=this.options,b=this.chart.renderer,a=e.graphic,k=e.shapeType,g=e.shapeArgs,m=e.partShapeArgs,p=e.clipRectArgs,v=e.partialFill,A=c.stacking&&!c.borderRadius,l=e.state,r=c.states[l||"normal"]||{},C="undefined"===typeof l?"attr":d;l=this.pointAttribs(e,l);r=n(this.chart.options.chart.animation,r.animation);if(e.isNull||!1===e.visible)a&&(e.graphic=a.destroy());else{if(a)a.rect[d](g);else e.graphic=
a=b.g("point").addClass(e.getClassName()).add(e.group||this.group),a.rect=b[k](f(g)).addClass(e.getClassName()).addClass("highcharts-partfill-original").add(a);m&&(a.partRect?(a.partRect[d](f(m)),a.partialClipRect[d](f(p))):(a.partialClipRect=b.clipRect(p.x,p.y,p.width,p.height),a.partRect=b[k](m).addClass("highcharts-partfill-overlay").add(a).clip(a.partialClipRect)));this.chart.styledMode||(a.rect[d](l,r).shadow(c.shadow,null,A),m&&(h(v)||(v={}),h(c.partialFill)&&(v=f(v,c.partialFill)),e=v.fill||
x(l.fill).brighten(-.3).get()||x(e.color||this.color).brighten(-.3).get(),l.fill=e,a.partRect[C](l,r).shadow(c.shadow,null,A)))}},drawPoints:function(){var e=this,f=e.getAnimationVerb();e.points.forEach(function(c){e.drawPoint(c,f)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var e=this.series;if(e.options.colorByPoint&&!this.options.color){var f=e.options.colors||e.chart.options.colors;var c=this.y%(f?f.length:
e.chart.options.chart.colorCount);f=f&&f[c];e.chart.styledMode||(this.color=f);this.options.colorIndex||(this.colorIndex=c)}else this.color||(this.color=e.color)},init:function(){w.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){w.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},getLabelConfig:function(){var e=w.prototype.getLabelConfig.call(this),f=this.series.yAxis.categories;e.x2=this.x2;e.yCategory=this.yCategory=
f&&f[this.y];return e},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});d(B,"afterGetSeriesExtremes",function(){var e=this.series,f;if(this.isXAxis){var c=n(this.dataMax,-Number.MAX_VALUE);e.forEach(function(b){b.x2Data&&b.x2Data.forEach(function(a){a>c&&(c=a,f=!0)})});f&&(this.dataMax=c)}});""});G(g,"parts-gantt/GanttSeries.js",[g["parts/Axis.js"],g["parts/Globals.js"],g["parts-gantt/TreeGridAxis.js"],g["parts/Utilities.js"]],function(g,d,
w,p){var x=p.isNumber,t=p.merge,y=p.pick,z=p.seriesType,v=p.splat,u=d.dateFormat;p=d.Series;var h=d.seriesTypes.xrange;w.compose(g);z("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var f=this.series,d=f.chart.tooltip,g=f.xAxis,h=f.tooltipOptions.dateTimeLabelFormats,p=g.options.startOfWeek,m=f.tooltipOptions,e=m.xDateFormat;f=this.options.milestone;var k="<b>"+(this.name||
this.yCategory)+"</b>";if(m.pointFormat)return this.tooltipFormatter(m.pointFormat);e||(e=v(d.getDateFormat(g.closestPointRange,this.start,p,h))[0]);d=u(e,this.start);g=u(e,this.end);k+="<br/>";return f?k+(d+"<br/>"):k+("Start: "+d+"<br/>End: ")+(g+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start","end","y"],keyboardMoveVertical:!1,translatePoint:function(f){h.prototype.translatePoint.call(this,
f);if(f.options.milestone){var d=f.shapeArgs;var g=d.height;f.shapeArgs={x:d.x-g/2,y:d.y,width:g,height:g}}},drawPoint:function(f,d){var g=this.options,n=this.chart.renderer,p=f.shapeArgs,m=f.plotY,e=f.graphic,k=f.selected&&"select",c=g.stacking&&!g.borderRadius;if(f.options.milestone)if(x(m)&&null!==f.y&&!1!==f.visible){p=n.symbols.diamond(p.x,p.y,p.width,p.height);if(e)e[d]({d:p});else f.graphic=n.path(p).addClass(f.getClassName(),!0).add(f.group||this.group);this.chart.styledMode||f.graphic.attr(this.pointAttribs(f,
k)).shadow(g.shadow,null,c)}else e&&(f.graphic=e.destroy());else h.prototype.drawPoint.call(this,f,d)},setData:p.prototype.setData,setGanttPointAliases:function(f){function d(d,g){"undefined"!==typeof g&&(f[d]=g)}d("x",y(f.start,f.x));d("x2",y(f.end,f.x2));d("partialFill",y(f.completed,f.partialFill));d("connect",y(f.dependency,f.connect))}},t(h.prototype.pointClass.prototype,{applyOptions:function(f,g){f=t(f);d.seriesTypes.gantt.prototype.setGanttPointAliases(f);return f=h.prototype.pointClass.prototype.applyOptions.call(this,
f,g)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});G(g,"parts-gantt/GanttChart.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,d){var w=d.isArray,p=d.merge,x=d.splat,t=g.Chart;g.ganttChart=function(d,z,v){var u="string"===typeof d||d.nodeName,h=z.series,f=g.getOptions(),n,y=z;z=arguments[u?1:0];w(z.xAxis)||(z.xAxis=[z.xAxis||{},{}]);z.xAxis=z.xAxis.map(function(d,g){1===
g&&(n=0);return p(f.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:n},d,{type:"datetime"})});z.yAxis=x(z.yAxis||{}).map(function(d){return p(f.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:d.categories?d.type:"treegrid"},d)});z.series=null;z=p(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},z,{isGantt:!0});z.series=y.series=h;z.series.forEach(function(f){f.data.forEach(function(f){g.seriesTypes.gantt.prototype.setGanttPointAliases(f)})});return u?new t(d,z,v):new t(z,z)}});
G(g,"parts/ScrollbarAxis.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,d){var w=d.addEvent,p=d.defined,x=d.pick;return function(){function d(){}d.compose=function(d,t){w(d,"afterInit",function(){var d=this;d.options&&d.options.scrollbar&&d.options.scrollbar.enabled&&(d.options.scrollbar.vertical=!d.horiz,d.options.startOnTick=d.options.endOnTick=!1,d.scrollbar=new t(d.chart.renderer,d.options.scrollbar,d.chart),w(d.scrollbar,"changed",function(u){var h=x(d.options&&d.options.min,
d.min),f=x(d.options&&d.options.max,d.max),n=p(d.dataMin)?Math.min(h,d.min,d.dataMin):h,t=(p(d.dataMax)?Math.max(f,d.max,d.dataMax):f)-n;p(h)&&p(f)&&(d.horiz&&!d.reversed||!d.horiz&&d.reversed?(h=n+t*this.to,n+=t*this.from):(h=n+t*(1-this.from),n+=t*(1-this.to)),x(this.options.liveRedraw,g.svg&&!g.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===u.DOMType||!p(u.DOMType)?d.setExtremes(n,h,!0,"mousemove"!==u.DOMType,u):this.setRange(this.from,this.to))}))});w(d,"afterRender",function(){var d=Math.min(x(this.options.min,
this.min),this.min,x(this.dataMin,this.min)),g=Math.max(x(this.options.max,this.max),this.max,x(this.dataMax,this.max)),h=this.scrollbar,f=this.axisTitleMargin+(this.titleOffset||0),n=this.chart.scrollbarsOffsets,t=this.options.margin||0;h&&(this.horiz?(this.opposite||(n[1]+=f),h.position(this.left,this.top+this.height+2+n[1]-(this.opposite?t:0),this.width,this.height),this.opposite||(n[1]+=t),f=1):(this.opposite&&(n[0]+=f),h.position(this.left+this.width+2+n[0]-(this.opposite?0:t),this.top,this.width,
this.height),this.opposite&&(n[0]+=t),f=0),n[f]+=h.size+h.options.margin,isNaN(d)||isNaN(g)||!p(this.min)||!p(this.max)||this.min===this.max?h.setRange(0,1):(n=(this.min-d)/(g-d),d=(this.max-d)/(g-d),this.horiz&&!this.reversed||!this.horiz&&this.reversed?h.setRange(n,d):h.setRange(1-d,1-n)))});w(d,"afterGetOffset",function(){var d=this.horiz?2:1,g=this.scrollbar;g&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[d]+=g.size+g.options.margin)})};return d}()});G(g,"parts/Scrollbar.js",[g["parts/Axis.js"],
g["parts/Globals.js"],g["parts/ScrollbarAxis.js"],g["parts/Utilities.js"]],function(g,d,w,p){var x=p.addEvent,t=p.correctFloat,y=p.defined,z=p.destroyObjectProperties,v=p.fireEvent,u=p.merge,h=p.pick,f=p.removeEvent;p=d.defaultOptions;var n=d.hasTouch,D=d.isTouchDevice,F=d.swapXY=function(f,e){e&&f.forEach(function(e){for(var c=e.length,b,a=0;a<c;a+=2)b=e[a+1],"number"===typeof b&&(e[a+1]=e[a+2],e[a+2]=b)});return f},B=function(){function d(e,d,c){this._events=[];this.from=this.chartY=this.chartX=
0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=c;this.options=d;this.renderer=c.renderer;this.init(e,d,c)}d.prototype.addEvents=function(){var e=this.options.inverted?[1,0]:[0,1],d=this.scrollbarButtons,c=this.scrollbarGroup.element,b=this.track.element,a=this.mouseDownHandler.bind(this),
f=this.mouseMoveHandler.bind(this),g=this.mouseUpHandler.bind(this);e=[[d[e[0]].element,"click",this.buttonToMinClick.bind(this)],[d[e[1]].element,"click",this.buttonToMaxClick.bind(this)],[b,"click",this.trackClick.bind(this)],[c,"mousedown",a],[c.ownerDocument,"mousemove",f],[c.ownerDocument,"mouseup",g]];n&&e.push([c,"touchstart",a],[c.ownerDocument,"touchmove",f],[c.ownerDocument,"touchend",g]);e.forEach(function(a){x.apply(null,a)});this._events=e};d.prototype.buttonToMaxClick=function(e){var d=
(this.to-this.from)*h(this.options.step,.2);this.updatePosition(this.from+d,this.to+d);v(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};d.prototype.buttonToMinClick=function(e){var d=t(this.to-this.from)*h(this.options.step,.2);this.updatePosition(t(this.from-d),t(this.to-d));v(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};d.prototype.cursorToScrollbarPosition=function(e){var d=this.options;d=d.minWidth>this.calculatedWidth?d.minWidth:0;return{chartX:(e.chartX-
this.x-this.xOffset)/(this.barWidth-d),chartY:(e.chartY-this.y-this.yOffset)/(this.barWidth-d)}};d.prototype.destroy=function(){var e=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(e){this[e]&&this[e].destroy&&(this[e]=this[e].destroy())},this);e&&this===e.scrollbar&&(e.scrollbar=null,z(e.scrollbarButtons))};d.prototype.drawScrollbarButton=function(e){var d=this.renderer,c=this.scrollbarButtons,b=this.options,a=this.size;var f=
d.g().add(this.group);c.push(f);f=d.rect().addClass("highcharts-scrollbar-button").add(f);this.chart.styledMode||f.attr({stroke:b.buttonBorderColor,"stroke-width":b.buttonBorderWidth,fill:b.buttonBackgroundColor});f.attr(f.crisp({x:-.5,y:-.5,width:a+1,height:a+1,r:b.buttonBorderRadius},f.strokeWidth()));f=d.path(F([["M",a/2+(e?-1:1),a/2-3],["L",a/2+(e?-1:1),a/2+3],["L",a/2+(e?2:-2),a/2]],b.vertical)).addClass("highcharts-scrollbar-arrow").add(c[e]);this.chart.styledMode||f.attr({fill:b.buttonArrowColor})};
d.prototype.init=function(e,f,c){this.scrollbarButtons=[];this.renderer=e;this.userOptions=f;this.options=u(d.defaultOptions,f);this.chart=c;this.size=h(this.options.size,this.options.height);f.enabled&&(this.render(),this.addEvents())};d.prototype.mouseDownHandler=function(e){e=this.chart.pointer.normalize(e);e=this.cursorToScrollbarPosition(e);this.chartX=e.chartX;this.chartY=e.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};d.prototype.mouseMoveHandler=function(e){var d=this.chart.pointer.normalize(e),
c=this.options.vertical?"chartY":"chartX",b=this.initPositions||[];!this.grabbedCenter||e.touches&&0===e.touches[0][c]||(d=this.cursorToScrollbarPosition(d)[c],c=this[c],c=d-c,this.hasDragged=!0,this.updatePosition(b[0]+c,b[1]+c),this.hasDragged&&v(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:e.type,DOMEvent:e}))};d.prototype.mouseUpHandler=function(e){this.hasDragged&&v(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:e.type,DOMEvent:e});this.grabbedCenter=
this.hasDragged=this.chartX=this.chartY=null};d.prototype.position=function(e,d,c,b){var a=this.options.vertical,f=0,g=this.rendered?"animate":"attr";this.x=e;this.y=d+this.trackBorderWidth;this.width=c;this.xOffset=this.height=b;this.yOffset=f;a?(this.width=this.yOffset=c=f=this.size,this.xOffset=d=0,this.barWidth=b-2*c,this.x=e+=this.options.margin):(this.height=this.xOffset=b=d=this.size,this.barWidth=c-2*b,this.y+=this.options.margin);this.group[g]({translateX:e,translateY:this.y});this.track[g]({width:c,
height:b});this.scrollbarButtons[1][g]({translateX:a?0:c-d,translateY:a?b-f:0})};d.prototype.removeEvents=function(){this._events.forEach(function(e){f.apply(null,e)});this._events.length=0};d.prototype.render=function(){var e=this.renderer,d=this.options,c=this.size,b=this.chart.styledMode,a;this.group=a=e.g("scrollbar").attr({zIndex:d.zIndex,translateY:-99999}).add();this.track=e.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:d.trackBorderRadius||0,height:c,width:c}).add(a);b||this.track.attr({fill:d.trackBackgroundColor,
stroke:d.trackBorderColor,"stroke-width":d.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=e.g().add(a);this.scrollbar=e.rect().addClass("highcharts-scrollbar-thumb").attr({height:c,width:c,r:d.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=e.path(F([["M",-3,c/4],["L",-3,2*c/3],["M",0,c/4],["L",0,2*c/3],["M",3,c/4],["L",3,2*c/3]],d.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);
b||(this.scrollbar.attr({fill:d.barBackgroundColor,stroke:d.barBorderColor,"stroke-width":d.barBorderWidth}),this.scrollbarRifles.attr({stroke:d.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};d.prototype.setRange=function(e,d){var c=this.options,b=c.vertical,a=c.minWidth,f=this.barWidth,g,h=!this.rendered||this.hasDragged||
this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(y(f)){e=Math.max(e,0);var k=Math.ceil(f*e);this.calculatedWidth=g=t(f*Math.min(d,1)-k);g<a&&(k=(f-a+g)*e,g=a);a=Math.floor(k+this.xOffset+this.yOffset);f=g/2-.5;this.from=e;this.to=d;b?(this.scrollbarGroup[h]({translateY:a}),this.scrollbar[h]({height:g}),this.scrollbarRifles[h]({translateY:f}),this.scrollbarTop=a,this.scrollbarLeft=0):(this.scrollbarGroup[h]({translateX:a}),this.scrollbar[h]({width:g}),this.scrollbarRifles[h]({translateX:f}),
this.scrollbarLeft=a,this.scrollbarTop=0);12>=g?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===c.showFull&&(0>=e&&1<=d?this.group.hide():this.group.show());this.rendered=!0}};d.prototype.trackClick=function(e){var d=this.chart.pointer.normalize(e),c=this.to-this.from,b=this.y+this.scrollbarTop,a=this.x+this.scrollbarLeft;this.options.vertical&&d.chartY>b||!this.options.vertical&&d.chartX>a?this.updatePosition(this.from+c,this.to+c):this.updatePosition(this.from-c,this.to-c);v(this,
"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:e})};d.prototype.update=function(e){this.destroy();this.init(this.chart.renderer,u(!0,this.options,e),this.chart)};d.prototype.updatePosition=function(e,d){1<d&&(e=t(1-t(d-e)),d=1);0>e&&(d=t(d-e),e=0);this.from=e;this.to=d};d.defaultOptions={height:D?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",
buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return d}();d.Scrollbar||(p.scrollbar=u(!0,B.defaultOptions,p.scrollbar),d.Scrollbar=B,w.compose(g,B));return d.Scrollbar});G(g,"parts/RangeSelector.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,d){function w(c){this.init(c)}var p=d.addEvent,x=d.createElement,t=d.css,y=d.defined,z=d.destroyObjectProperties,
v=d.discardElement,u=d.extend,h=d.fireEvent,f=d.isNumber,n=d.merge,D=d.objectEach,F=d.pick,B=d.pInt,m=d.splat,e=g.Axis;d=g.Chart;var k=g.defaultOptions;u(k,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});k.lang=n(k.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});w.prototype={clickButton:function(c,
b){var a=this.chart,d=this.buttonOptions[c],g=a.xAxis[0],h=a.scroller&&a.scroller.getUnionExtremes()||g||{},k=h.dataMin,n=h.dataMax,A=g&&Math.round(Math.min(g.max,F(n,g.max))),l=d.type;h=d._range;var r,C=d.dataGrouping;if(null!==k&&null!==n){a.fixedRange=h;C&&(this.forcedDataGrouping=!0,e.prototype.setDataGrouping.call(g||{chart:this.chart},C,!1),this.frozenStates=d.preserveDataGrouping);if("month"===l||"year"===l)if(g){l={range:d,max:A,chart:a,dataMin:k,dataMax:n};var J=g.minFromRange.call(l);f(l.newMax)&&
(A=l.newMax)}else h=d;else if(h)J=Math.max(A-h,k),A=Math.min(J+h,n);else if("ytd"===l)if(g)"undefined"===typeof n&&(k=Number.MAX_VALUE,n=Number.MIN_VALUE,a.series.forEach(function(a){a=a.xData;k=Math.min(a[0],k);n=Math.max(a[a.length-1],n)}),b=!1),A=this.getYTDExtremes(n,k,a.time.useUTC),J=r=A.min,A=A.max;else{this.deferredYTDClick=c;return}else"all"===l&&g&&(J=k,A=n);J+=d._offsetMin;A+=d._offsetMax;this.setSelected(c);if(g)g.setExtremes(J,A,F(b,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:d});
else{var I=m(a.options.xAxis)[0];var t=I.range;I.range=h;var u=I.min;I.min=r;p(a,"load",function(){I.range=t;I.min=u})}}},setSelected:function(c){this.selected=this.options.selected=c},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(c){var b=this,a=c.options.rangeSelector,e=a.buttons||[].concat(b.defaultButtons),d=a.selected,f=function(){var a=
b.minInput,c=b.maxInput;a&&a.blur&&h(a,"blur");c&&c.blur&&h(c,"blur")};b.chart=c;b.options=a;b.buttons=[];b.buttonOptions=e;this.unMouseDown=p(c.container,"mousedown",f);this.unResize=p(c,"resize",f);e.forEach(b.computeButtonRange);"undefined"!==typeof d&&e[d]&&this.clickButton(d,!1);p(c,"load",function(){c.xAxis&&c.xAxis[0]&&p(c.xAxis[0],"setExtremes",function(a){this.max-this.min!==c.fixedRange&&"rangeSelectorButton"!==a.trigger&&"updatedData"!==a.trigger&&b.forcedDataGrouping&&!b.frozenStates&&
this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var c=this,b=this.chart,a=b.xAxis[0],e=Math.round(a.max-a.min),d=!a.hasVisibleSeries,g=b.scroller&&b.scroller.getUnionExtremes()||a,h=g.dataMin,k=g.dataMax;b=c.getYTDExtremes(k,h,b.time.useUTC);var n=b.min,l=b.max,r=c.selected,m=f(r),p=c.options.allButtonsEnabled,I=c.buttons;c.buttonOptions.forEach(function(b,f){var g=b._range,q=b.type,C=b.count||1,A=I[f],J=0,t=b._offsetMax-b._offsetMin;b=f===r;var u=g>k-h,S=g<a.minRange,v=!1,w=!1;g=g===
e;("month"===q||"year"===q)&&e+36E5>=864E5*{month:28,year:365}[q]*C-t&&e-36E5<=864E5*{month:31,year:366}[q]*C+t?g=!0:"ytd"===q?(g=l-n+t===e,v=!b):"all"===q&&(g=a.max-a.min>=k-h,w=!b&&m&&g);q=!p&&(u||S||w||d);C=b&&g||g&&!m&&!v||b&&c.frozenStates;q?J=3:C&&(m=!0,J=2);A.state!==J&&(A.setState(J),0===J&&r===f&&c.setSelected(null))})},computeButtonRange:function(c){var b=c.type,a=c.count||1,e={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(e[b])c._range=e[b]*a;else if("month"===
b||"year"===b)c._range=864E5*{month:30,year:365}[b]*a;c._offsetMin=F(c.offsetMin,0);c._offsetMax=F(c.offsetMax,0);c._range+=c._offsetMax-c._offsetMin},setInputValue:function(c,b){var a=this.chart.options.rangeSelector,e=this.chart.time,d=this[c+"Input"];y(b)&&(d.previousValue=d.HCTime,d.HCTime=b);d.value=e.dateFormat(a.inputEditDateFormat||"%Y-%m-%d",d.HCTime);this[c+"DateBox"].attr({text:e.dateFormat(a.inputDateFormat||"%b %e, %Y",d.HCTime)})},showInput:function(c){var b=this.inputGroup,a=this[c+
"DateBox"];t(this[c+"Input"],{left:b.translateX+a.x+"px",top:b.translateY+"px",width:a.width-2+"px",height:a.height-2+"px",border:"2px solid silver"})},hideInput:function(c){t(this[c+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(c)},drawInput:function(c){function b(){var b=l.value,c=(m.inputDateParser||Date.parse)(b),d=e.xAxis[0],g=e.scroller&&e.scroller.xAxis?e.scroller.xAxis:d,r=g.dataMin;g=g.dataMax;c!==l.previousValue&&(l.previousValue=c,f(c)||(c=b.split("-"),c=Date.UTC(B(c[0]),
B(c[1])-1,B(c[2]))),f(c)&&(e.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),A?c>a.maxInput.HCTime?c=void 0:c<r&&(c=r):c<a.minInput.HCTime?c=void 0:c>g&&(c=g),"undefined"!==typeof c&&d.setExtremes(A?c:d.min,A?d.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var a=this,e=a.chart,d=e.renderer.style||{},h=e.renderer,m=e.options.rangeSelector,p=a.div,A="min"===c,l,r,C=this.inputGroup;this[c+"Label"]=r=h.label(k.lang[A?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(C);
C.offset+=r.width+5;this[c+"DateBox"]=h=h.label("",C.offset).addClass("highcharts-range-input").attr({padding:2,width:m.inputBoxWidth||90,height:m.inputBoxHeight||17,"text-align":"center"}).on("click",function(){a.showInput(c);a[c+"Input"].focus()});e.styledMode||h.attr({stroke:m.inputBoxBorderColor||"#cccccc","stroke-width":1});h.add(C);C.offset+=h.width+(A?10:0);this[c+"Input"]=l=x("input",{name:c,className:"highcharts-range-selector",type:"text"},{top:e.plotTop+"px"},p);e.styledMode||(r.css(n(d,
m.labelStyle)),h.css(n({color:"#333333"},d,m.inputStyle)),t(l,u({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:d.fontSize,fontFamily:d.fontFamily,top:"-9999em"},m.inputStyle)));l.onfocus=function(){a.showInput(c)};l.onblur=function(){l===g.doc.activeElement&&b();a.hideInput(c);l.blur()};l.onchange=b;l.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var c=this.chart,b=c.options.rangeSelector;c="top"===b.verticalAlign?c.plotTop-c.axisOffset[0]:
0;return{buttonTop:c+b.buttonPosition.y,inputTop:c+b.inputPosition.y-10}},getYTDExtremes:function(c,b,a){var e=this.chart.time,d=new e.Date(c),f=e.get("FullYear",d);a=a?e.Date.UTC(f,0,1):+new e.Date(f,0,1);b=Math.max(b||0,a);d=d.getTime();return{max:Math.min(c||d,d),min:b}},render:function(c,b){var a=this,e=a.chart,d=e.renderer,f=e.container,g=e.options,h=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,m=k.lang,l=a.div,r=g.rangeSelector,n=F(g.chart.style&&g.chart.style.zIndex,
0)+1;g=r.floating;var p=a.buttons;l=a.inputGroup;var t=r.buttonTheme,u=r.buttonPosition,v=r.inputPosition,L=r.inputEnabled,w=t&&t.states,y=e.plotLeft,z=a.buttonGroup,B,D=a.options.verticalAlign,Q=e.legend,G=Q&&Q.options,R=u.y,P=v.y,O=e.hasLoaded,T=O?"animate":"attr",N=0,M=0;if(!1!==r.enabled){a.rendered||(a.group=B=d.g("range-selector-group").attr({zIndex:7}).add(),a.buttonGroup=z=d.g("range-selector-buttons").add(B),a.zoomText=d.text(m.rangeSelectorZoom,0,15).add(z),e.styledMode||(a.zoomText.css(r.labelStyle),
t["stroke-width"]=F(t["stroke-width"],0)),a.buttonOptions.forEach(function(b,c){p[c]=d.button(b.text,0,0,function(e){var d=b.events&&b.events.click,f;d&&(f=d.call(b,e));!1!==f&&a.clickButton(c);a.isActive=!0},t,w&&w.hover,w&&w.select,w&&w.disabled).attr({"text-align":"center"}).add(z)}),!1!==L&&(a.div=l=x("div",null,{position:"relative",height:0,zIndex:n}),f.parentNode.insertBefore(l,f),a.inputGroup=l=d.g("input-group").add(B),l.offset=0,a.drawInput("min"),a.drawInput("max")));a.zoomText[T]({x:F(y+
u.x,y)});var U=F(y+u.x,y)+a.zoomText.getBBox().width+5;a.buttonOptions.forEach(function(a,b){p[b][T]({x:U});U+=p[b].width+F(r.buttonSpacing,5)});y=e.plotLeft-e.spacing[3];a.updateButtonStates();h&&this.titleCollision(e)&&"top"===D&&"right"===u.align&&u.y+z.getBBox().height-12<(h.y||0)+h.height&&(N=-40);f=u.x-e.spacing[3];"right"===u.align?f+=N-y:"center"===u.align&&(f-=y/2);z.align({y:u.y,width:z.getBBox().width,align:u.align,x:f},!0,e.spacingBox);a.group.placed=O;a.buttonGroup.placed=O;!1!==L&&(N=
h&&this.titleCollision(e)&&"top"===D&&"right"===v.align&&v.y-l.getBBox().height-12<(h.y||0)+h.height+e.spacing[0]?-40:0,"left"===v.align?f=y:"right"===v.align&&(f=-Math.max(e.axisOffset[1],-N)),l.align({y:v.y,width:l.getBBox().width,align:v.align,x:v.x+f-2},!0,e.spacingBox),h=l.alignAttr.translateX+l.alignOptions.x-N+l.getBBox().x+2,f=l.alignOptions.width,m=z.alignAttr.translateX+z.getBBox().x,y=z.getBBox().width+20,(v.align===u.align||m+y>h&&h+f>m&&R<P+l.getBBox().height)&&l.attr({translateX:l.alignAttr.translateX+
(e.axisOffset[1]>=-N?0:-N),translateY:l.alignAttr.translateY+z.getBBox().height+10}),a.setInputValue("min",c),a.setInputValue("max",b),a.inputGroup.placed=O);a.group.align({verticalAlign:D},!0,e.spacingBox);c=a.group.getBBox().height+20;b=a.group.alignAttr.translateY;"bottom"===D&&(Q=G&&"bottom"===G.verticalAlign&&G.enabled&&!G.floating?Q.legendHeight+F(G.margin,10):0,c=c+Q-20,M=b-c-(g?0:r.y)-(e.titleOffset?e.titleOffset[2]:0)-10);if("top"===D)g&&(M=0),e.titleOffset&&e.titleOffset[0]&&(M=e.titleOffset[0]),
M+=e.margin[0]-e.spacing[0]||0;else if("middle"===D)if(P===R)M=0>P?b+void 0:b;else if(P||R)M=0>P||0>R?M-Math.min(P,R):b-c+NaN;a.group.translate(r.x,r.y+Math.floor(M));!1!==L&&(a.minInput.style.marginTop=a.group.translateY+"px",a.maxInput.style.marginTop=a.group.translateY+"px");a.rendered=!0}},getHeight:function(){var c=this.options,b=this.group,a=c.y,e=c.buttonPosition.y,d=c.inputPosition.y;if(c.height)return c.height;c=b?b.getBBox(!0).height+13+a:0;b=Math.min(d,e);if(0>d&&0>e||0<d&&0<e)c+=Math.abs(b);
return c},titleCollision:function(c){return!(c.options.title.text||c.options.subtitle.text)},update:function(c){var b=this.chart;n(!0,b.options.rangeSelector,c);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var c=this,b=c.minInput,a=c.maxInput;c.unMouseDown();c.unResize();z(c.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);a&&(a.onfocus=a.onblur=a.onchange=null);D(c,function(a,b){a&&"chart"!==b&&(a.destroy?a.destroy():a.nodeType&&v(this[b]));a!==w.prototype[b]&&(c[b]=null)},
this)}};e.prototype.minFromRange=function(){var c=this.range,b=c.type,a=this.max,e=this.chart.time,d=function(a,c){var d="year"===b?"FullYear":"Month",f=new e.Date(a),l=e.get(d,f);e.set(d,f,l+c);l===e.get(d,f)&&e.set("Date",f,0);return f.getTime()-a};if(f(c)){var g=a-c;var h=c}else g=a+d(a,-c.count),this.chart&&(this.chart.fixedRange=a-g);var k=F(this.dataMin,Number.MIN_VALUE);f(g)||(g=k);g<=k&&(g=k,"undefined"===typeof h&&(h=d(g,c.count)),this.newMax=Math.min(g+h,this.dataMax));f(a)||(g=void 0);
return g};g.RangeSelector||(p(d,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new w(this))}),p(d,"beforeRender",function(){var c=this.axes,b=this.rangeSelector;b&&(f(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),c.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),c=b.options.verticalAlign,b.options.floating||("bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=!0)))}),
p(d,"update",function(c){var b=c.options.rangeSelector;c=this.rangeSelector;var a=this.extraBottomMargin,e=this.extraTopMargin;b&&b.enabled&&!y(c)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new w(this));this.extraTopMargin=this.extraBottomMargin=!1;c&&(c.render(),b=b&&b.verticalAlign||c.options&&c.options.verticalAlign,c.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==a||this.extraTopMargin!==e)&&(this.isDirtyBox=
!0)}),p(d,"render",function(){var c=this.rangeSelector;c&&!c.options.floating&&(c.render(),c=c.options.verticalAlign,"bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=!0))}),p(d,"getMargins",function(){var c=this.rangeSelector;c&&(c=c.getHeight(),this.extraTopMargin&&(this.plotTop+=c),this.extraBottomMargin&&(this.marginBottom+=c))}),d.prototype.callbacks.push(function(c){function b(){a=c.xAxis[0].getExtremes();d=c.legend;h=null===e||void 0===e?void 0:e.options.verticalAlign;
f(a.min)&&e.render(a.min,a.max);e&&d.display&&"top"===h&&h===d.options.verticalAlign&&(g=n(c.spacingBox),g.y="vertical"===d.options.layout?c.plotTop:g.y+e.getHeight(),d.group.placed=!1,d.align(g))}var a,e=c.rangeSelector,d,g,h;if(e){var k=p(c.xAxis[0],"afterSetExtremes",function(a){e.render(a.min,a.max)});var m=p(c,"redraw",b);b()}p(c,"destroy",function(){e&&(m(),k())})}),g.RangeSelector=w)});G(g,"parts/NavigatorAxis.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,d){var w=g.isTouchDevice,
p=d.addEvent,x=d.correctFloat,t=d.defined,y=d.isNumber,z=d.pick,v=function(){function d(d){this.axis=d}d.prototype.destroy=function(){this.axis=void 0};d.prototype.toFixedRange=function(d,f,g,p){var h=this.axis,n=h.chart;n=n&&n.fixedRange;var m=(h.pointRange||0)/2;d=z(g,h.translate(d,!0,!h.horiz));f=z(p,h.translate(f,!0,!h.horiz));h=n&&(f-d)/n;t(g)||(d=x(d+m));t(p)||(f=x(f-m));.7<h&&1.3>h&&(p?d=f-n:f=d+n);y(d)&&y(f)||(d=f=void 0);return{min:d,max:f}};return d}();return function(){function d(){}d.compose=
function(d){d.keepProps.push("navigatorAxis");p(d,"init",function(){this.navigatorAxis||(this.navigatorAxis=new v(this))});p(d,"zoom",function(d){var f=this.chart.options,g=f.navigator,h=this.navigatorAxis,p=f.chart.pinchType,m=f.rangeSelector;f=f.chart.zoomType;this.isXAxis&&(g&&g.enabled||m&&m.enabled)&&("y"===f?d.zoomed=!1:(!w&&"xy"===f||w&&"xy"===p)&&this.options.range&&(g=h.previousZoom,t(d.newMin)?h.previousZoom=[this.min,this.max]:g&&(d.newMin=g[0],d.newMax=g[1],h.previousZoom=void 0)));"undefined"!==
typeof d.zoomed&&d.preventDefault()})};d.AdditionsClass=v;return d}()});G(g,"parts/Navigator.js",[g["parts/Axis.js"],g["parts/Color.js"],g["parts/Globals.js"],g["parts/NavigatorAxis.js"],g["parts/Scrollbar.js"],g["parts/Utilities.js"]],function(g,d,w,p,x,t){d=d.parse;var y=t.addEvent,z=t.clamp,v=t.correctFloat,u=t.defined,h=t.destroyObjectProperties,f=t.erase,n=t.extend,D=t.find,F=t.isArray,B=t.isNumber,m=t.merge,e=t.pick,k=t.removeEvent,c=t.splat;t=w.Chart;var b=w.defaultOptions,a=w.hasTouch,q=w.isTouchDevice,
G=w.Series,H=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,B);if(b.length)return Math[a].apply(0,b)};var O="undefined"===typeof w.seriesTypes.areaspline?"line":"areaspline";n(b,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:d("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:O,
fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,
className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});w.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height||
0;return[["M",-a-1,.5],["L",a,.5],["L",a,e+.5],["L",-a-1,e+.5],["L",-a-1,.5],["M",-b,4],["L",-b,e-3],["M",b-1,4],["L",b-1,e-3]]};var E=function(){function d(a){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}d.prototype.drawHandle=
function(a,b,c,d){var e=this.navigatorOptions.handles.height;this.handles[b][d](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(a,10)+.5-e)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-e/2-1)})};d.prototype.drawOutline=function(a,b,c,d){var e=this.navigatorOptions.maskInside,f=this.outline.strokeWidth(),g=f/2,l=f%2/2;f=this.outlineHeight;var h=this.scrollbarHeight||0,r=this.size,k=this.left-h,m=this.top;c?
(k-=g,c=m+b+l,b=m+a+l,l=[["M",k+f,m-h-l],["L",k+f,c],["L",k,c],["L",k,b],["L",k+f,b],["L",k+f,m+r+h]],e&&l.push(["M",k+f,c-g],["L",k+f,b+g])):(a+=k+h-l,b+=k+h-l,m+=g,l=[["M",k,m],["L",a,m],["L",a,m+f],["L",b,m+f],["L",b,m],["L",k+r+2*h,m]],e&&l.push(["M",a-g,m],["L",b+g,m]));this.outline[d]({d:l})};d.prototype.drawMasks=function(a,b,c,d){var e=this.left,f=this.top,g=this.height;if(c){var l=[e,e,e];var h=[f,f+a,f+b];var r=[g,g,g];var k=[a,b-a,this.size-b]}else l=[e,e+a,e+b],h=[f,f,f],r=[a,b-a,this.size-
b],k=[g,g,g];this.shades.forEach(function(a,b){a[d]({x:l[b],y:h[b],width:r[b],height:k[b]})})};d.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,l){a.shades[l]=e.rect().addClass("highcharts-navigator-mask"+(1===l?"-inside":"-outside")).add(f);d.styledMode||a.shades[l].attr({fill:c?b.maskFill:
"rgba(0,0,0,0)"}).css(1===l&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var l=
b.handles;a.handles[c].attr({fill:l.backgroundColor,stroke:l.borderColor,"stroke-width":l.lineWidth}).css(g)}})};d.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&delete a.baseSeries.navigatorSeries});this.destroy();m(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};d.prototype.render=function(a,b,c,d){var f=this.chart,g=this.scrollbarHeight,l,h=this.xAxis,k=h.pointRange||0;var r=h.navigatorAxis.fake?f.xAxis[0]:h;var m=this.navigatorEnabled,n,
p=this.rendered;var q=f.inverted;var C=f.xAxis[0].minRange,t=f.xAxis[0].options.maxRange;if(!this.hasDragged||u(c)){a=v(a-k/2);b=v(b+k/2);if(!B(a)||!B(b))if(p)c=0,d=e(h.width,r.width);else return;this.left=e(h.left,f.plotLeft+g+(q?f.plotWidth:0));this.size=n=l=e(h.len,(q?f.plotHeight:f.plotWidth)-2*g);f=q?g:l+2*g;c=e(c,h.toPixels(a,!0));d=e(d,h.toPixels(b,!0));B(c)&&Infinity!==Math.abs(c)||(c=0,d=f);a=h.toValue(c,!0);b=h.toValue(d,!0);var w=Math.abs(v(b-a));w<C?this.grabbedLeft?c=h.toPixels(b-C-k,
!0):this.grabbedRight&&(d=h.toPixels(a+C+k,!0)):u(t)&&v(w-k)>t&&(this.grabbedLeft?c=h.toPixels(b-t-k,!0):this.grabbedRight&&(d=h.toPixels(a+t+k,!0)));this.zoomedMax=z(Math.max(c,d),0,n);this.zoomedMin=z(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,n);this.range=this.zoomedMax-this.zoomedMin;n=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);m&&(this.navigatorGroup.attr({visibility:"visible"}),p=p&&!this.hasDragged?"animate":"attr",this.drawMasks(c,n,q,p),this.drawOutline(c,
n,q,p),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,q,p),this.drawHandle(n,1,q,p)));this.scrollbar&&(q?(q=this.top-g,r=this.left-g+(m||!r.opposite?0:(r.titleOffset||0)+r.axisTitleMargin),g=l+2*g):(q=this.top+(m?this.height:-g),r=this.left-g),this.scrollbar.position(r,q,f,g),this.scrollbar.setRange(this.zoomedMin/(l||1),this.zoomedMax/(l||1)));this.rendered=!0}};d.prototype.addMouseEvents=function(){var b=this,c=b.chart,d=c.container,e=[],f,g;b.mouseMoveHandler=f=function(a){b.onMouseMove(a)};
b.mouseUpHandler=g=function(a){b.onMouseUp(a)};e=b.getPartsEvents("mousedown");e.push(y(c.renderTo,"mousemove",f),y(d.ownerDocument,"mouseup",g));a&&(e.push(y(c.renderTo,"touchmove",f),y(d.ownerDocument,"touchend",g)),e.concat(b.getPartsEvents("touchstart")));b.eventsToUnbind=e;b.series&&b.series[0]&&e.push(y(b.series[0].xAxis,"foundExtremes",function(){c.navigator.modifyNavigatorAxisExtremes()}))};d.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,
f){c.push(y(e.element,a,function(a){b[d+"Mousedown"](a,f)}))})});return c};d.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,e=this.zoomedMin,f=this.left,g=this.size,l=this.range,h=a.chartX;c.inverted&&(h=a.chartY,f=this.top);if(1===b)this.grabbedCenter=h,this.fixedWidth=l,this.dragOffset=h-e;else{a=h-f-l/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+l>=g)if(a=g-l,this.reversedExtremes){a-=l;var k=this.getUnionExtremes().dataMin}else var m=this.getUnionExtremes().dataMax;
a!==e&&(this.fixedWidth=l,b=d.navigatorAxis.toFixedRange(a,a+l,k,m),u(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};d.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=
null};d.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,f=b.navigatorSize,g=b.range,l=b.dragOffset,h=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),c=a.chartX,h&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&(b.hasDragged=!0,c<l?c=l:c>f+l-g&&(c=f+l-g),b.render(0,0,c-l,c-l+g)),b.hasDragged&&b.scrollbar&&e(b.scrollbar.options.liveRedraw,
w.svg&&!q&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};d.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,e=a.DOMEvent||a,f=b.inverted,g=this.rendered&&!this.hasDragged?"animate":"attr",l=Math.round(this.zoomedMax),h=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var k=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var m=
this.fixedExtreme;this.zoomedMax===this.size&&(m=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(k=this.reversedExtremes?d.dataMax:d.dataMin);c=c.navigatorAxis.toFixedRange(this.zoomedMin,this.zoomedMax,k,m);u(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:e})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=
this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(h,l,f,g),this.outline&&this.drawOutline(h,l,f,g),this.navigatorOptions.handles.enabled&&Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(h,0,f,g),this.drawHandle(l,1,f,g)))};d.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};d.prototype.removeBaseSeriesEvents=
function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){k(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&k(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};d.prototype.init=function(a){var b=a.options,c=b.navigator,d=c.enabled,f=b.scrollbar,h=f.enabled;b=d?c.height:0;var l=h?f.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=l;this.scrollbarEnabled=
h;this.navigatorEnabled=d;this.navigatorOptions=c;this.scrollbarOptions=f;this.outlineHeight=b+l;this.opposite=e(c.opposite,!(d||!a.inverted));var k=this;d=k.baseSeries;f=a.xAxis.length;h=a.yAxis.length;var n=d&&d[0]&&d[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;k.navigatorEnabled?(k.xAxis=new g(a,m({breaks:n.options.breaks,ordinal:n.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:f,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,
endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[l,0,-l,0],width:b}:{offsets:[0,-l,0,l],height:b})),k.yAxis=new g(a,m(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,offset:0,index:h,isInternal:!0,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),d||c.series.data?k.updateNavigatorSeries(!1):0===a.series.length&&(k.unbindRedraw=y(a,"beforeRedraw",function(){0<a.series.length&&!k.series&&(k.setBaseSeries(),k.unbindRedraw())})),k.reversedExtremes=a.inverted&&!k.xAxis.reversed||
!a.inverted&&k.xAxis.reversed,k.renderElements(),k.addMouseEvents()):(k.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),f=d.len-2*l,g=H("min",d.options.min,e.dataMin);d=H("max",d.options.max,e.dataMax)-g;return c?b*d/f+g:f*(b-g)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},k.xAxis.navigatorAxis.axis=k.xAxis,k.xAxis.navigatorAxis.toFixedRange=p.AdditionsClass.prototype.toFixedRange.bind(k.xAxis.navigatorAxis));
a.options.scrollbar.enabled&&(a.scrollbar=k.scrollbar=new x(a.renderer,m(a.options.scrollbar,{margin:k.navigatorEnabled?0:10,vertical:a.inverted}),a),y(k.scrollbar,"changed",function(b){var c=k.size,d=c*this.to;c*=this.from;k.hasDragged=k.scrollbar.hasDragged;k.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){k.onMouseUp(b)})}));k.addBaseSeriesEvents();k.addChartEvents()};d.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],
c=this.xAxis,d=c.options,f=b.options,g;a&&null===b.dataMin||(g={dataMin:e(d&&d.min,H("min",f.min,b.dataMin,c.dataMin,c.min)),dataMax:e(d&&d.max,H("max",f.max,b.dataMax,c.dataMax,c.max))});return g};d.prototype.setBaseSeries=function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?D(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==
a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};d.prototype.updateNavigatorSeries=function(a,d){var f=this,g=f.chart,h=f.baseSeries,l,p,q=f.navigatorOptions.series,r,t={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},u=f.series=(f.series||[]).filter(function(a){var b=a.baseSeries;
return 0>h.indexOf(b)?(b&&(k(b,"updatedData",f.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});h&&h.length&&h.forEach(function(a){var c=a.navigatorSeries,k=n({color:a.color,visible:a.visible},F(q)?b.navigator.series:q);c&&!1===f.navigatorOptions.adaptToUpdatedData||(t.name="Navigator "+h.length,l=a.options||{},r=l.navigatorOptions||{},p=m(l,t,k,r),p.pointRange=e(k.pointRange,r.pointRange,b.plotOptions[p.type||"line"].pointRange),k=r.data||k.data,f.hasNavigatorData=f.hasNavigatorData||
!!k,p.data=k||l.data&&l.data.slice(0),c&&c.options?c.update(p,d):(a.navigatorSeries=g.initSeries(p),a.navigatorSeries.baseSeries=a,u.push(a.navigatorSeries)))});if(q.data&&(!h||!h.length)||F(q))f.hasNavigatorData=!1,q=c(q),q.forEach(function(a,c){t.name="Navigator "+(u.length+1);p=m(b.navigator.series,{color:g.series[c]&&!g.series[c].options.isInternal&&g.series[c].color||g.options.colors[c]||g.options.colors[0]},t,a);p.data=a.data;p.data&&(f.hasNavigatorData=!0,u.push(g.initSeries(p)))});a&&this.addBaseSeriesEvents()};
d.prototype.addBaseSeriesEvents=function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&y(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);b.forEach(function(b){y(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});y(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&y(b,"updatedData",this.updatedDataHandler);y(b,"remove",function(){this.navigatorSeries&&(f(a.series,this.navigatorSeries),
u(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};d.prototype.getBaseSeriesMin=function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};d.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};d.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,
b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var f=a.stickToMin,g=a.stickToMax,h=e(this.options.overscroll,0),k=a.series&&a.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(f){var n=c;var p=n+b}g&&(p=d+h,f||(n=Math.max(c,p-b,a.getBaseSeriesMin(k&&k.xData?k.xData[0]:-Number.MAX_VALUE))));m&&(f||g)&&B(n)&&(this.min=this.userMin=n,this.max=this.userMax=p)}a.stickToMin=a.stickToMax=null};d.prototype.updatedDataHandler=function(){var a=
this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=B(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};d.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(y(this.chart,"redraw",
function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),y(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};d.prototype.destroy=function(){this.removeEvents();this.xAxis&&(f(this.chart.xAxis,this.xAxis),f(this.chart.axes,
this.xAxis));this.yAxis&&(f(this.chart.yAxis,this.yAxis),f(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){h(a)},this)};return d}();w.Navigator||(w.Navigator=E,p.compose(g),y(t,"beforeShowResetZoom",function(){var a=
this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!q&&"x"===a.chart.zoomType||q&&"x"===a.chart.pinchType))return!1}),y(t,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new E(this)}),y(t,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var f=b.yAxis;var g=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-g-b.height:this.spacing[3]+
g,b.top=this.plotTop+g):(b.left=this.plotLeft+g,b.top=b.navigatorOptions.top||this.chartHeight-b.height-g-this.spacing[2]-(this.rangeSelector&&this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?a.legendHeight+e(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&f&&(this.inverted?d.options.left=f.options.left=b.left:d.options.top=f.options.top=b.top,d.setAxisSize(),f.setAxisSize())}}),y(t,"update",function(a){var b=a.options.navigator||
{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(m(!0,this.options.navigator,b),m(!0,this.options.scrollbar,c),delete a.options.navigator,delete a.options.scrollbar)}),y(t,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new E(this),e(a.redraw,!0)&&this.redraw(a.animation))}),y(t,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),
y(G,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),t.prototype.callbacks.push(function(a){var b=a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));w.Navigator=E;return w.Navigator});G(g,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map