/*
 Highcharts Gantt JS v8.0.4 (2020-04-28)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(c){"object"===typeof module&&module.exports?(c["default"]=c,module.exports=c):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(B){c(B);c.Highcharts=B;return c}):c("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(c){function B(c,t,y,w){c.hasOwnProperty(t)||(c[t]=w.apply(null,y))}c=c?c._modules:{};B(c,"parts-gantt/GridAxis.js",[c["parts/Axis.js"],c["parts/Globals.js"],c["parts/Tick.js"],c["parts/Utilities.js"]],function(c,t,y,
w){var m=w.addEvent,r=w.defined,z=w.erase,A=w.find,n=w.isArray,d=w.isNumber,C=w.merge,q=w.pick,x=w.timeUnits,h=w.wrap,p=t.dateFormat,e=t.Chart,b=function(a){var f=a.options;f.labels||(f.labels={});f.labels.align=q(f.labels.align,"center");a.categories||(f.showLastLabel=!1);a.labelRotation=0;f.labels.rotation=0};"";c.prototype.getMaxLabelDimensions=function(a,f){var k={width:0,height:0};f.forEach(function(f){f=a[f];if(w.isObject(f,!0)){var b=w.isObject(f.label,!0)?f.label:{};f=b.getBBox?b.getBBox().height:
0;b.textStr&&!d(b.textPxLength)&&(b.textPxLength=b.getBBox().width);b=d(b.textPxLength)?Math.round(b.textPxLength):0;k.height=Math.max(f,k.height);k.width=Math.max(b,k.width)}});return k};t.dateFormats.W=function(a){a=new this.Date(a);var f=(this.get("Day",a)+6)%7,k=new this.Date(a.valueOf());this.set("Date",k,this.get("Date",a)-f+3);f=new this.Date(this.get("FullYear",k),0,1);4!==this.get("Day",f)&&(this.set("Month",a,0),this.set("Date",a,1+(11-this.get("Day",f))%7));return(1+Math.floor((k.valueOf()-
f.valueOf())/6048E5)).toString()};t.dateFormats.E=function(a){return p("%a",a,!0).charAt(0)};m(e,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.grid&&a.grid.columns||[]).forEach(function(f){f.setAxisSize();f.setAxisTranslation()})})});m(y,"afterGetLabelPosition",function(a){var f=this.label,k=this.axis,b=k.reversed,e=k.chart,g=k.options.grid||{},h=k.options.labels,F=h.align,v=l.Side[k.side],u=a.tickmarkOffset,D=k.tickPositions,E=this.pos-u;D=d(D[a.index+1])?D[a.index+1]-u:k.max+u;
var p=k.tickSize("tick",!0);u=n(p)?p[0]:0;p=p&&p[1]/2;if(!0===g.enabled){if("top"===v){g=k.top+k.offset;var c=g-u}else"bottom"===v?(c=e.chartHeight-k.bottom+k.offset,g=c+u):(g=k.top+k.len-k.translate(b?D:E),c=k.top+k.len-k.translate(b?E:D));"right"===v?(v=e.chartWidth-k.right+k.offset,b=v+u):"left"===v?(b=k.left+k.offset,v=b-u):(v=Math.round(k.left+k.translate(b?D:E))-p,b=Math.round(k.left+k.translate(b?E:D))-p);this.slotWidth=b-v;a.pos.x="left"===F?v:"right"===F?b:v+(b-v)/2;a.pos.y=c+(g-c)/2;e=e.renderer.fontMetrics(h.style.fontSize,
f.element);f=f.getBBox().height;h.useHTML?a.pos.y+=e.b+-(f/2):(f=Math.round(f/e.h),a.pos.y+=(e.b-(e.h-e.f))/2+-((f-1)*e.h/2));a.pos.x+=k.horiz&&h.x||0}});var g=function(){function a(f){this.axis=f}a.prototype.isOuterAxis=function(){var f=this.axis,a=f.grid.columnIndex,b=f.linkedParent&&f.linkedParent.grid.columns||f.grid.columns,e=a?f.linkedParent:f,g=-1,l=0;f.chart[f.coll].forEach(function(a,b){a.side!==f.side||a.options.isInternal||(l=b,a===e&&(g=b))});return l===g&&(d(a)?b.length===a:!0)};return a}(),
l=function(){function a(){}a.compose=function(f){c.keepProps.push("grid");h(f.prototype,"unsquish",a.wrapUnsquish);m(f,"init",a.onInit);m(f,"afterGetOffset",a.onAfterGetOffset);m(f,"afterGetTitlePosition",a.onAfterGetTitlePosition);m(f,"afterInit",a.onAfterInit);m(f,"afterRender",a.onAfterRender);m(f,"afterSetAxisTranslation",a.onAfterSetAxisTranslation);m(f,"afterSetOptions",a.onAfterSetOptions);m(f,"afterSetOptions",a.onAfterSetOptions2);m(f,"afterSetScale",a.onAfterSetScale);m(f,"afterTickSize",
a.onAfterTickSize);m(f,"trimTicks",a.onTrimTicks);m(f,"destroy",a.onDestroy)};a.onAfterGetOffset=function(){var f=this.grid;(f&&f.columns||[]).forEach(function(f){f.getOffset()})};a.onAfterGetTitlePosition=function(f){if(!0===(this.options.grid||{}).enabled){var b=this.axisTitle,e=this.height,g=this.horiz,l=this.left,d=this.offset,h=this.opposite,v=this.options.title,u=void 0===v?{}:v;v=this.top;var D=this.width,E=this.tickSize(),p=b&&b.getBBox().width,c=u.x||0,n=u.y||0,x=q(u.margin,g?5:10);b=this.chart.renderer.fontMetrics(u.style&&
u.style.fontSize,b).f;E=(g?v+e:l)+E[0]/2*(h?-1:1)*(g?1:-1)+(this.side===a.Side.bottom?b:0);f.titlePosition.x=g?l-p/2-x+c:E+(h?D:0)+d+c;f.titlePosition.y=g?E-(h?e:0)+(h?b:-b)/2+d+n:v-x+n}};a.onAfterInit=function(){var f=this.chart,a=this.options.grid;a=void 0===a?{}:a;var e=this.userOptions;a.enabled&&(b(this),h(this,"labelFormatter",function(a){var f=this.axis,b=this.value,k=f.tickPositions,e=(f.isLinked?f.linkedParent:f).series[0],g=b===k[0];k=b===k[k.length-1];e=e&&A(e.options.data,function(a){return a[f.isXAxis?
"x":"y"]===b});this.isFirst=g;this.isLast=k;this.point=e;return a.call(this)}));if(a.columns)for(var g=this.grid.columns=[],l=this.grid.columnIndex=0;++l<a.columns.length;){var d=C(e,a.columns[a.columns.length-l-1],{linkedTo:0,type:"category"});delete d.grid.columns;d=new c(this.chart,d);d.grid.isColumn=!0;d.grid.columnIndex=l;z(f.axes,d);z(f[this.coll],d);g.push(d)}};a.onAfterRender=function(){var f=this.grid,b=this.options,e=this.chart.renderer;if(!0===(b.grid||{}).enabled){this.maxLabelDimensions=
this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.grid&&this.grid.isOuterAxis()&&this.axisLine){var g=b.lineWidth;if(g){var l=this.getLinePath(g),d=l[0],h=l[1],v=(this.tickSize("tick")[0]-1)*(this.side===a.Side.top||this.side===a.Side.left?-1:1);"M"===d[0]&&"L"===h[0]&&(this.horiz?(d[2]+=v,h[2]+=v):(d[1]+=v,h[1]+=v));this.grid.axisLineExtra?this.grid.axisLineExtra.animate({d:l}):(this.grid.axisLineExtra=e.path(l).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),
e.styledMode||this.grid.axisLineExtra.attr({stroke:b.lineColor,"stroke-width":g}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(f&&f.columns||[]).forEach(function(a){a.render()})}};a.onAfterSetAxisTranslation=function(){var a=this.tickPositions&&this.tickPositions.info,b=this.options,e=b.grid||{},g=this.userOptions.labels||{};this.horiz&&(!0===e.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),a&&b.dateTimeLabelFormats&&b.labels&&!r(g.align)&&(!1===b.dateTimeLabelFormats[a.unitName].range||
1<a.count)&&(b.labels.align="left",r(g.x)||(b.labels.x=3)))};a.onAfterSetOptions=function(a){var b=this.options;a=a.userOptions;var f=b&&w.isObject(b.grid,!0)?b.grid:{};if(!0===f.enabled){var e=C(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,
rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(r(a.linkedTo)&&!r(a.tickPixelInterval)&&(e.tickPixelInterval=350),r(a.tickPixelInterval)||!r(a.linkedTo)||r(a.tickPositioner)||r(a.tickInterval)||(e.tickPositioner=function(a,b){var f=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(f){var g,k=e.units;for(g=0;g<k.length;g++)if(k[g][0]===
f.unitName){var l=g;break}if(k[l+1]){var d=k[l+1][0];var h=(k[l+1][1]||[1])[0]}else"year"===f.unitName&&(d="year",h=10*f.count);f=x[d];this.tickInterval=f*h;return this.getTimeTicks({unitRange:f,count:h,unitName:d},a,b,this.options.startOfWeek)}}));C(!0,this.options,e);this.horiz&&(b.minPadding=q(a.minPadding,0),b.maxPadding=q(a.maxPadding,0));d(b.grid.borderWidth)&&(b.tickWidth=b.lineWidth=f.borderWidth)}};a.onAfterSetOptions2=function(a){a=(a=a.userOptions)&&a.grid||{};var b=a.columns;a.enabled&&
b&&C(!0,this.options,b[b.length-1])};a.onAfterSetScale=function(){(this.grid.columns||[]).forEach(function(a){a.setScale()})};a.onAfterTickSize=function(a){var b=c.defaultLeftAxisOptions,f=this.horiz,e=this.maxLabelDimensions,g=this.options.grid;g=void 0===g?{}:g;g.enabled&&e&&(b=2*Math.abs(b.labels.x),f=f?g.cellHeight||b+e.height:b+e.width,n(a.tickSize)?a.tickSize[0]=f:a.tickSize=[f])};a.onDestroy=function(a){var b=this.grid;(b.columns||[]).forEach(function(b){b.destroy(a.keepEvents)});b.columns=
void 0};a.onInit=function(a){a=a.userOptions||{};var b=a.grid||{};b.enabled&&r(b.borderColor)&&(a.tickColor=a.lineColor=b.borderColor);this.grid||(this.grid=new g(this))};a.onTrimTicks=function(){var a=this.options,b=this.categories,e=this.tickPositions,g=e[0],l=e[e.length-1],d=this.linkedParent&&this.linkedParent.min||this.min,h=this.linkedParent&&this.linkedParent.max||this.max,v=this.tickInterval;!0!==(a.grid||{}).enabled||b||!this.horiz&&!this.isLinked||(g<d&&g+v>d&&!a.startOnTick&&(e[0]=d),l>
h&&l-v<h&&!a.endOnTick&&(e[e.length-1]=h))};a.wrapUnsquish=function(a){var b=this.options.grid;return!0===(void 0===b?{}:b).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))};return a}();(function(a){a=a.Side||(a.Side={});a[a.top=0]="top";a[a.right=1]="right";a[a.bottom=2]="bottom";a[a.left=3]="left"})(l||(l={}));return l});B(c,"parts-gantt/Tree.js",[c["parts/Utilities.js"]],function(c){var t=c.extend,y=c.isNumber,w=c.pick,m=function(c,m){var n=c.reduce(function(d,
c){var n=w(c.parent,"");"undefined"===typeof d[n]&&(d[n]=[]);d[n].push(c);return d},{});Object.keys(n).forEach(function(d,c){var q=n[d];""!==d&&-1===m.indexOf(d)&&(q.forEach(function(d){c[""].push(d)}),delete c[d])});return n},r=function(c,m,n,d,C,q){var x=0,h=0,p=q&&q.after,e=q&&q.before;m={data:d,depth:n-1,id:c,level:n,parent:m};var b,g;"function"===typeof e&&e(m,q);e=(C[c]||[]).map(function(e){var a=r(e.id,c,n+1,e,C,q),f=e.start;e=!0===e.milestone?f:e.end;b=!y(b)||f<b?f:b;g=!y(g)||e>g?e:g;x=x+
1+a.descendants;h=Math.max(a.height+1,h);return a});d&&(d.start=w(d.start,b),d.end=w(d.end,g));t(m,{children:e,descendants:x,height:h});"function"===typeof p&&p(m,q);return m};return{getListOfParents:m,getNode:r,getTree:function(c,t){var n=c.map(function(d){return d.id});c=m(c,n);return r("",null,1,null,c,t)}}});B(c,"parts-gantt/TreeGridTick.js",[c["parts/Utilities.js"]],function(c){var t=c.addEvent,y=c.defined,w=c.isObject,m=c.isNumber,r=c.pick,z=c.wrap,A;(function(c){function d(){this.treeGrid||
(this.treeGrid=new p(this))}function n(e,b){e=e.treeGrid;var g=!e.labelIcon,l=b.renderer,a=b.xy,f=b.options,k=f.width,d=f.height,c=a.x-k/2-f.padding;a=a.y-d/2;var h=b.collapsed?90:180,p=b.show&&m(a),n=e.labelIcon;n||(e.labelIcon=n=l.path(l.symbols[f.type](f.x,f.y,k,d)).addClass("highcharts-label-icon").add(b.group));p||n.attr({y:-9999});l.styledMode||n.attr({"stroke-width":1,fill:r(b.color,"#666666")}).css({cursor:"pointer",stroke:f.lineColor,strokeWidth:f.lineWidth});n[g?"attr":"animate"]({translateX:c,
translateY:a,rotation:h})}function q(e,b,g,d,a,f,k,c,h){var l=r(this.options&&this.options.labels,f);f=this.pos;var p=this.axis,n="treegrid"===p.options.type;e=e.apply(this,[b,g,d,a,l,k,c,h]);n&&(b=l&&w(l.symbol,!0)?l.symbol:{},l=l&&m(l.indentation)?l.indentation:0,f=(f=(p=p.treeGrid.mapOfPosToGridNode)&&p[f])&&f.depth||1,e.x+=b.width+2*b.padding+(f-1)*l);return e}function x(e){var b=this,g=b.pos,l=b.axis,a=b.label,f=l.treeGrid.mapOfPosToGridNode,d=l.options,c=r(b.options&&b.options.labels,d&&d.labels),
h=c&&w(c.symbol,!0)?c.symbol:{},p=(f=f&&f[g])&&f.depth;d="treegrid"===d.type;var x=-1<l.tickPositions.indexOf(g);g=l.chart.styledMode;d&&f&&a&&a.element&&a.addClass("highcharts-treegrid-node-level-"+p);e.apply(b,Array.prototype.slice.call(arguments,1));d&&a&&a.element&&f&&f.descendants&&0<f.descendants&&(l=l.treeGrid.isCollapsed(f),n(b,{color:!g&&a.styles&&a.styles.color||"",collapsed:l,group:a.parentGroup,options:h,renderer:a.renderer,show:x,xy:a.xy}),h="highcharts-treegrid-node-"+(l?"expanded":
"collapsed"),a.addClass("highcharts-treegrid-node-"+(l?"collapsed":"expanded")).removeClass(h),g||a.css({cursor:"pointer"}),[a,b.treeGrid.labelIcon].forEach(function(f){f&&!f.attachedTreeGridEvents&&(t(f.element,"mouseover",function(){a.addClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:"underline"})}),t(f.element,"mouseout",function(){var b=y(c.style)?c.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:b.textDecoration})}),
t(f.element,"click",function(){b.treeGrid.toggleCollapse()}),f.attachedTreeGridEvents=!0)}))}var h=!1;c.compose=function(e){h||(t(e,"init",d),z(e.prototype,"getLabelPosition",q),z(e.prototype,"renderLabel",x),e.prototype.collapse=function(b){this.treeGrid.collapse(b)},e.prototype.expand=function(b){this.treeGrid.expand(b)},e.prototype.toggleCollapse=function(b){this.treeGrid.toggleCollapse(b)},h=!0)};var p=function(){function e(b){this.tick=b}e.prototype.collapse=function(b){var e=this.tick,d=e.axis,
a=d.brokenAxis;a&&d.treeGrid.mapOfPosToGridNode&&(e=d.treeGrid.collapse(d.treeGrid.mapOfPosToGridNode[e.pos]),a.setBreaks(e,r(b,!0)))};e.prototype.expand=function(b){var e=this.tick,d=e.axis,a=d.brokenAxis;a&&d.treeGrid.mapOfPosToGridNode&&(e=d.treeGrid.expand(d.treeGrid.mapOfPosToGridNode[e.pos]),a.setBreaks(e,r(b,!0)))};e.prototype.toggleCollapse=function(b){var e=this.tick,d=e.axis,a=d.brokenAxis;a&&d.treeGrid.mapOfPosToGridNode&&(e=d.treeGrid.toggleCollapse(d.treeGrid.mapOfPosToGridNode[e.pos]),
a.setBreaks(e,r(b,!0)))};return e}();c.Additions=p})(A||(A={}));return A});B(c,"mixins/tree-series.js",[c["parts/Color.js"],c["parts/Utilities.js"]],function(c,t){var y=t.extend,w=t.isArray,m=t.isNumber,r=t.isObject,z=t.merge,A=t.pick;return{getColor:function(n,d){var m=d.index,q=d.mapOptionsToLevel,x=d.parentColor,h=d.parentColorIndex,p=d.series,e=d.colors,b=d.siblings,g=p.points,l=p.chart.options.chart,a;if(n){g=g[n.i];n=q[n.level]||{};if(q=g&&n.colorByPoint){var f=g.index%(e?e.length:l.colorCount);
var k=e&&e[f]}if(!p.chart.styledMode){e=g&&g.options.color;l=n&&n.color;if(a=x)a=(a=n&&n.colorVariation)&&"brightness"===a.key?c.parse(x).brighten(m/b*a.to).get():x;a=A(e,l,k,a,p.color)}var r=A(g&&g.options.colorIndex,n&&n.colorIndex,f,h,d.colorIndex)}return{color:a,colorIndex:r}},getLevelOptions:function(c){var d=null;if(r(c)){d={};var n=m(c.from)?c.from:1;var q=c.levels;var x={};var h=r(c.defaults)?c.defaults:{};w(q)&&(x=q.reduce(function(d,e){if(r(e)&&m(e.level)){var b=z({},e);var g="boolean"===
typeof b.levelIsConstant?b.levelIsConstant:h.levelIsConstant;delete b.levelIsConstant;delete b.level;e=e.level+(g?0:n-1);r(d[e])?y(d[e],b):d[e]=b}return d},{}));q=m(c.to)?c.to:1;for(c=0;c<=q;c++)d[c]=z({},h,r(x[c])?x[c]:{})}return d},setTreeValues:function q(d,c){var x=c.before,h=c.idRoot,p=c.mapIdToNode[h],e=c.points[d.i],b=e&&e.options||{},g=0,l=[];y(d,{levelDynamic:d.level-(("boolean"===typeof c.levelIsConstant?c.levelIsConstant:1)?0:p.level),name:A(e&&e.name,""),visible:h===d.id||("boolean"===
typeof c.visible?c.visible:!1)});"function"===typeof x&&(d=x(d,c));d.children.forEach(function(a,b){var f=y({},c);y(f,{index:b,siblings:d.children.length,visible:d.visible});a=q(a,f);l.push(a);a.visible&&(g+=a.val)});d.visible=0<g||d.visible;x=A(b.value,g);y(d,{children:l,childrenTotal:g,isLeaf:d.visible&&!g,val:x});return d},updateRootId:function(d){if(r(d)){var c=r(d.options)?d.options:{};c=A(d.rootNode,c.rootId,"");r(d.userOptions)&&(d.userOptions.rootId=c);d.rootNode=c}return c}}});B(c,"modules/broken-axis.src.js",
[c["parts/Axis.js"],c["parts/Globals.js"],c["parts/Utilities.js"],c["parts/Stacking.js"]],function(c,t,y,w){var m=y.addEvent,r=y.find,z=y.fireEvent,A=y.isArray,n=y.isNumber,d=y.pick,C=t.Series,q=function(){function n(c){this.hasBreaks=!1;this.axis=c}n.isInBreak=function(c,d){var e=c.repeat||Infinity,b=c.from,g=c.to-c.from;d=d>=b?(d-b)%e:e-(b-d)%e;return c.inclusive?d<=g:d<g&&0!==d};n.lin2Val=function(c){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return c;var e;for(e=0;e<d.length;e++){var b=d[e];
if(b.from>=c)break;else b.to<c?c+=b.len:n.isInBreak(b,c)&&(c+=b.len)}return c};n.val2Lin=function(c){var d=this.brokenAxis;d=d&&d.breakArray;if(!d)return c;var e=c,b;for(b=0;b<d.length;b++){var g=d[b];if(g.to<=c)e-=g.len;else if(g.from>=c)break;else if(n.isInBreak(g,c)){e-=c-g.from;break}}return e};n.prototype.findBreakAt=function(c,d){return r(d,function(e){return e.from<c&&c<e.to})};n.prototype.isInAnyBreak=function(c,m){var e=this.axis,b=e.options.breaks,g=b&&b.length,l;if(g){for(;g--;)if(n.isInBreak(b[g],
c)){var a=!0;l||(l=d(b[g].showPoints,!e.isXAxis))}var f=a&&m?a&&!l:a}return f};n.prototype.setBreaks=function(h,m){var e=this,b=e.axis,g=A(h)&&!!h.length;b.isDirty=e.hasBreaks!==g;e.hasBreaks=g;b.options.breaks=b.userOptions.breaks=h;b.forceRedraw=!0;b.series.forEach(function(b){b.isDirty=!0});g||b.val2lin!==n.val2Lin||(delete b.val2lin,delete b.lin2val);g&&(b.userOptions.ordinal=!1,b.lin2val=n.lin2Val,b.val2lin=n.val2Lin,b.setExtremes=function(b,a,f,d,g){if(e.hasBreaks){for(var k,l=this.options.breaks;k=
e.findBreakAt(b,l);)b=k.to;for(;k=e.findBreakAt(a,l);)a=k.from;a<b&&(a=b)}c.prototype.setExtremes.call(this,b,a,f,d,g)},b.setAxisTranslation=function(g){c.prototype.setAxisTranslation.call(this,g);e.unitLength=null;if(e.hasBreaks){g=b.options.breaks||[];var a=[],f=[],k=0,l,h=b.userMin||b.min,m=b.userMax||b.max,p=d(b.pointRangePadding,0),q;g.forEach(function(a){l=a.repeat||Infinity;n.isInBreak(a,h)&&(h+=a.to%l-h%l);n.isInBreak(a,m)&&(m-=m%l-a.from%l)});g.forEach(function(b){u=b.from;for(l=b.repeat||
Infinity;u-l>h;)u-=l;for(;u<h;)u+=l;for(q=u;q<m;q+=l)a.push({value:q,move:"in"}),a.push({value:q+(b.to-b.from),move:"out",size:b.breakSize})});a.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var v=0;var u=h;a.forEach(function(a){v+="in"===a.move?1:-1;1===v&&"in"===a.move&&(u=a.value);0===v&&(f.push({from:u,to:a.value,len:a.value-u-(a.size||0)}),k+=a.value-u-(a.size||0))});b.breakArray=e.breakArray=f;e.unitLength=m-h-k+p;z(b,"afterBreaks");b.staticScale?
b.transA=b.staticScale:e.unitLength&&(b.transA*=(m-b.min+p)/e.unitLength);p&&(b.minPixelPadding=b.transA*b.minPointOffset);b.min=h;b.max=m}});d(m,!0)&&b.chart.redraw()};return n}();t=function(){function c(){}c.compose=function(c,p){c.keepProps.push("brokenAxis");var e=C.prototype;e.drawBreaks=function(b,c){var e=this,a=e.points,f,g,h,m;if(b&&b.brokenAxis&&b.brokenAxis.hasBreaks){var p=b.brokenAxis;c.forEach(function(c){f=p&&p.breakArray||[];g=b.isXAxis?b.min:d(e.options.threshold,b.min);a.forEach(function(a){m=
d(a["stack"+c.toUpperCase()],a[c]);f.forEach(function(c){if(n(g)&&n(m)){h=!1;if(g<c.from&&m>c.to||g>c.from&&m<c.from)h="pointBreak";else if(g<c.from&&m>c.from&&m<c.to||g>c.from&&m>c.to&&m<c.from)h="pointInBreak";h&&z(b,h,{point:a,brk:c})}})})})}};e.gappedPath=function(){var b=this.currentDataGrouping,c=b&&b.gapSize;b=this.options.gapSize;var e=this.points.slice(),a=e.length-1,f=this.yAxis,d;if(b&&0<a)for("value"!==this.options.gapUnit&&(b*=this.basePointRange),c&&c>b&&c>=this.basePointRange&&(b=c),
d=void 0;a--;)d&&!1!==d.visible||(d=e[a+1]),c=e[a],!1!==d.visible&&!1!==c.visible&&(d.x-c.x>b&&(d=(c.x+d.x)/2,e.splice(a+1,0,{isNull:!0,x:d}),f.stacking&&this.options.stacking&&(d=f.stacking.stacks[this.stackKey][d]=new w(f,f.options.stackLabels,!1,d,this.stack),d.total=0)),d=c);return this.getGraphPath(e)};m(c,"init",function(){this.brokenAxis||(this.brokenAxis=new q(this))});m(c,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});m(c,
"afterSetTickPositions",function(){var b=this.brokenAxis;if(b&&b.hasBreaks){var c=this.tickPositions,d=this.tickPositions.info,a=[],e;for(e=0;e<c.length;e++)b.isInAnyBreak(c[e])||a.push(c[e]);this.tickPositions=a;this.tickPositions.info=d}});m(c,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});m(p,"afterGeneratePoints",function(){var b=this.options.connectNulls,c=this.points,e=this.xAxis,a=this.yAxis;if(this.isDirty)for(var d=c.length;d--;){var k=
c[d],h=!(null===k.y&&!1===b)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(k.x,!0)||a&&a.brokenAxis&&a.brokenAxis.isInAnyBreak(k.y,!0));k.visible=h?!1:!1!==k.options.visible}});m(p,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,d(this.pointArrayMap,["y"]))})};return c}();t.compose(c,C);return t});B(c,"parts-gantt/TreeGridAxis.js",[c["parts/Axis.js"],c["parts-gantt/GridAxis.js"],c["parts/Tick.js"],c["parts-gantt/Tree.js"],c["parts-gantt/TreeGridTick.js"],c["mixins/tree-series.js"],
c["parts/Utilities.js"]],function(c,t,y,w,m,r,z){var A=z.addEvent,n=z.find,d=z.fireEvent,C=z.isNumber,q=z.isObject,x=z.isString,h=z.merge,p=z.pick,e=z.wrap,b;(function(b){function c(a,b){var c=a.collapseStart||0;a=a.collapseEnd||0;a>=b&&(c-=.5);return{from:c,to:a,showPoints:!1}}function a(a,b,c){var e=[],d=[],f={},g={},u=-1,l="boolean"===typeof b?b:!1;a=w.getTree(a,{after:function(a){a=g[a.pos];var b=0,c=0;a.children.forEach(function(a){c+=(a.descendants||0)+1;b=Math.max((a.height||0)+1,b)});a.descendants=
c;a.height=b;a.collapsed&&d.push(a)},before:function(a){var b=q(a.data,!0)?a.data:{},c=x(b.name)?b.name:"",d=f[a.parent];d=q(d,!0)?g[d.pos]:null;var h=function(a){return a.name===c},k;l&&q(d,!0)&&(k=n(d.children,h))?(h=k.pos,k.nodes.push(a)):h=u++;g[h]||(g[h]=k={depth:d?d.depth+1:0,name:c,nodes:[a],children:[],pos:h},-1!==h&&e.push(c),q(d,!0)&&d.children.push(k));x(a.id)&&(f[a.id]=a);k&&!0===b.collapsed&&(k.collapsed=!0);a.pos=h}});g=function(a,b){var c=function(a,d,e){var f=d+(-1===d?0:b-1),g=(f-
d)/2,u=d+g;a.nodes.forEach(function(a){var b=a.data;q(b,!0)&&(b.y=d+(b.seriesIndex||0),delete b.seriesIndex);a.pos=u});e[u]=a;a.pos=u;a.tickmarkOffset=g+.5;a.collapseStart=f+.5;a.children.forEach(function(a){c(a,f+1,e);f=(a.collapseEnd||0)-.5});a.collapseEnd=f+.5;return e};return c(a["-1"],-1,{})}(g,c);return{categories:e,mapOfIdToNode:f,mapOfPosToGridNode:g,collapsedNodes:d,tree:a}}function f(b){b.target.axes.filter(function(a){return"treegrid"===a.options.type}).forEach(function(c){var d=c.options||
{},e=d.labels,f=d.uniqueNames,g=0;if(!c.treeGrid.mapOfPosToGridNode||c.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty}))d=c.series.reduce(function(a,b){b.visible&&((b.options.data||[]).forEach(function(b){q(b,!0)&&(b.seriesIndex=g,a.push(b))}),!0===f&&g++);return a},[]),d=a(d,f||!1,!0===f?g:1),c.categories=d.categories,c.treeGrid.mapOfPosToGridNode=d.mapOfPosToGridNode,c.hasNames=!0,c.treeGrid.tree=d.tree,c.series.forEach(function(a){var b=(a.options.data||[]).map(function(a){return q(a,
!0)?h(a):a});a.visible&&a.setData(b,!1)}),c.treeGrid.mapOptionsToLevel=r.getLevelOptions({defaults:e,from:1,levels:e&&e.levels,to:c.treeGrid.tree&&c.treeGrid.tree.height}),"beforeRender"===b.type&&(c.treeGrid.collapsedNodes=d.collapsedNodes)})}function g(a,b){var c=this.treeGrid.mapOptionsToLevel||{},d=this.ticks,e=d[b],f;if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var g=this.treeGrid.mapOfPosToGridNode[b];(c=c[g.depth])&&(f={labels:c});e?(e.parameters.category=g.name,e.options=
f,e.addLabel()):d[b]=new y(this,b,void 0,void 0,{category:g.name,tickmarkOffset:g.tickmarkOffset,options:f})}else a.apply(this,Array.prototype.slice.call(arguments,1))}function z(a){var b=this.options;b=(b=b&&b.labels)&&C(b.indentation)?b.indentation:0;var c=a.apply(this,Array.prototype.slice.call(arguments,1));if("treegrid"===this.options.type&&this.treeGrid.mapOfPosToGridNode){var d=this.treeGrid.mapOfPosToGridNode[-1].height||0;c.width+=b*(d-1)}return c}function B(b,c,d){var e=this,g="treegrid"===
d.type;e.treeGrid||(e.treeGrid=new F(e));g&&(A(c,"beforeRender",f),A(c,"beforeRedraw",f),A(c,"addSeries",function(b){b.options.data&&(b=a(b.options.data,d.uniqueNames||!1,1),e.treeGrid.collapsedNodes=(e.treeGrid.collapsedNodes||[]).concat(b.collapsedNodes))}),A(e,"foundExtremes",function(){e.treeGrid.collapsedNodes&&e.treeGrid.collapsedNodes.forEach(function(a){var b=e.treeGrid.collapse(a);e.brokenAxis&&(e.brokenAxis.setBreaks(b,!1),e.treeGrid.collapsedNodes&&(e.treeGrid.collapsedNodes=e.treeGrid.collapsedNodes.filter(function(b){return a.collapseStart!==
b.collapseStart||a.collapseEnd!==b.collapseEnd})))})}),d=h({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},d,{reversed:!0,grid:{columns:void 0}}));b.apply(e,[c,d]);g&&(e.hasNames=!0,e.options.showLastLabel=!0)}function H(a){var b=this.options;"treegrid"===b.type?(this.min=p(this.userMin,b.min,this.dataMin),this.max=p(this.userMax,b.max,this.dataMax),d(this,"foundExtremes"),
this.setAxisTranslation(!0),this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.treeGrid.mapOfPosToGridNode?this.treeGrid.getTickPositions():[]):a.apply(this,Array.prototype.slice.call(arguments,1))}var G=!1;b.compose=function(a){G||(t.compose(a),e(a.prototype,"generateTick",g),e(a.prototype,"getMaxLabelDimensions",z),e(a.prototype,"init",B),e(a.prototype,"setTickInterval",H),m.compose(y),G=!0)};var F=function(){function a(a){this.axis=a}a.prototype.collapse=function(a){var b=this.axis,
d=b.options.breaks||[];a=c(a,b.max);d.push(a);return d};a.prototype.expand=function(a){var b=this.axis,d=b.options.breaks||[],e=c(a,b.max);return d.reduce(function(a,b){b.to===e.to&&b.from===e.from||a.push(b);return a},[])};a.prototype.getTickPositions=function(){var a=this.axis;return Object.keys(a.treeGrid.mapOfPosToGridNode||{}).reduce(function(b,c){c=+c;!(a.min<=c&&a.max>=c)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(c)||b.push(c);return b},[])};a.prototype.isCollapsed=function(a){var b=this.axis,
d=b.options.breaks||[],e=c(a,b.max);return d.some(function(a){return a.from===e.from&&a.to===e.to})};a.prototype.toggleCollapse=function(a){return this.isCollapsed(a)?this.expand(a):this.collapse(a)};return a}();b.Additions=F})(b||(b={}));c.prototype.utils={getNode:w.getNode};return b});B(c,"parts-gantt/TreeGrid.js",[c["parts/Axis.js"],c["parts-gantt/TreeGridAxis.js"]],function(c,t){t.compose(c)});B(c,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map